"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const CityChase = require(path.resolve(__dirname, "..", "game-hub-server", "citychase"));

assert.ok(Object.keys(CityChase.BOARD.NODES).length >= 140, "원작 사진처럼 촘촘한 이동 칸이 필요합니다.");
assert.equal(CityChase.BOARD.BUILDINGS.length, 7, "수색 건물은 7곳이어야 합니다.");
assert.equal(CityChase.TRICK_CARD_COUNT, 9);
assert.equal(CityChase.CHECK_CARD_COUNT, 6);

function assignSeats(game) {
  const limits = CityChase.requiredTeamCounts(game.players.length);
  game.players.forEach((player, index) => {
    const team = index < limits.police ? "police" : "thief";
    const slot = index < limits.police ? index + 1 : index - limits.police + 1;
    assert.equal(CityChase.chooseSeat(game, player.id, team, slot).ok, true);
  });
  assert.equal(CityChase.lobbyReady(game), true);
}

const expectedPoliceCounts = { 2: 1, 3: 1, 4: 2, 5: 2, 6: 3 };
for (let count = 2; count <= 6; count += 1) {
  const teamGame = CityChase.createGame("player-1", "1번");
  for (let index = 2; index <= count; index += 1) CityChase.addPlayer(teamGame, `player-${index}`, `${index}번`);
  assert.equal(CityChase.startGame(teamGame).ok, false, "참가순서만으로 팀을 자동 배정하면 안 됩니다.");
  assignSeats(teamGame);
  assert.equal(CityChase.startGame(teamGame).ok, true);
  assert.equal(teamGame.players.filter(player => player.team === "police").length, expectedPoliceCounts[count]);
  assert.equal(teamGame.players.filter(player => player.team === "thief").length, count - expectedPoliceCounts[count]);
  assert.ok(teamGame.pawns.every(pawn => pawn.controllerIds.length >= 1), `${count}인 게임에서 모든 말을 누군가 맡아야 합니다.`);
  assert.ok(teamGame.players.every(player => player.pawnIds.length >= 1), `${count}인 게임에서 모든 참가자가 말을 맡아야 합니다.`);
}

const leavingGame = CityChase.createGame("p1", "하나");
CityChase.addPlayer(leavingGame, "p2", "두리");
CityChase.addPlayer(leavingGame, "p3", "세나");
CityChase.addPlayer(leavingGame, "p4", "네모");
assignSeats(leavingGame);
CityChase.removePlayer(leavingGame, "p4");
assert.equal(leavingGame.players.find(player => player.id === "p2").team, null, "인원 감소로 닫힌 슬롯에 참가자가 남으면 안 됩니다.");
assert.equal(CityChase.lobbyReady(leavingGame), false, "인원 변동 뒤에는 필요한 슬롯을 다시 선택해야 합니다.");

const game = CityChase.createGame("police", "경찰 대표");
CityChase.addPlayer(game, "thief", "도둑 대표");
assert.equal(CityChase.chooseSeat(game, "police", "police", 1).ok, true);
assert.equal(CityChase.chooseSeat(game, "thief", "police", 1).ok, false, "다른 학생의 슬롯으로 이동할 수 없어야 합니다.");
assert.equal(CityChase.chooseSeat(game, "thief", "thief", 1).ok, true);
assert.equal(CityChase.stateFor(game, "police").lobbyReady, true);
assert.deepEqual(CityChase.stateFor(game, "police").teamLimits, { police: 1, thief: 1 });
assert.equal(CityChase.chooseSeat(game, "thief", "thief", 1).ok, true, "자기 슬롯을 다시 누르면 자리에서 나올 수 있어야 합니다.");
assert.equal(CityChase.lobbyReady(game), false);
assert.equal(CityChase.chooseSeat(game, "thief", "thief", 1).ok, true);
assert.equal(CityChase.startGame(game).ok, true);
assert.equal(game.phase, "setup");
assert.deepEqual(game.players.map(player => player.team), ["police", "thief"]);
assert.equal(game.pawns.length, 6, "참가 인원과 관계없이 경찰·도둑 말 6개를 모두 사용합니다.");
assert.ok(game.pawns.filter(pawn => pawn.team === "police").every(pawn => pawn.controllerIds.includes("police")));
assert.ok(game.pawns.filter(pawn => pawn.team === "thief").every(pawn => pawn.controllerIds.includes("thief")));

assert.equal(CityChase.placeSecrets(game, "thief", { gems: ["market", "air"], undercover: "burger" }).ok, false);
assert.equal(CityChase.placeSecrets(game, "police", { gems: ["market", "air"], undercover: "burger" }).ok, true);
assert.equal(game.phase, "playing");
const policeView = CityChase.stateFor(game, "police");
const thiefView = CityChase.stateFor(game, "thief");
assert.equal(policeView.buildings.find(item => item.id === "market").content, "gem");
assert.equal(thiefView.buildings.find(item => item.id === "market").content, "hidden", "도둑 화면에는 비밀 배치가 노출되면 안 됩니다.");
assert.deepEqual(thiefView.buildings.map(item => item.content), Array(7).fill("hidden"));

assert.equal(game.turnPawnId, undefined);
assert.equal(CityChase.currentPawn(game).id, "thief-1");
assert.equal(CityChase.roll(game, "police", 2).ok, false, "상대 팀의 말을 대신 움직일 수 없어야 합니다.");
assert.equal(CityChase.roll(game, "thief", 2).ok, true);
assert.equal(CityChase.stateFor(game, "thief").validMoves.includes("p0"), true);
assert.equal(CityChase.moveStep(game, "thief", "p0").ok, true);
const firstDenseRoad = CityChase.BOARD.neighbors("p0", "thief").find(item => item.id !== "hideout").id;
assert.equal(CityChase.moveStep(game, "thief", firstDenseRoad).ok, true);
assert.equal(CityChase.currentPawn(game).id, "thief-2", "정확한 칸 수를 이동하면 다음 말 차례가 됩니다.");

const hideGame = CityChase.createGame("p", "경찰");
CityChase.addPlayer(hideGame, "t", "도둑");
assignSeats(hideGame);
CityChase.startGame(hideGame);
CityChase.placeSecrets(hideGame, "p", { gems: ["market", "air"], undercover: "burger" });
assert.equal(CityChase.hide(hideGame, "t").ok, true, "비밀기지에서는 이동 대신 숨을 수 있어야 합니다.");
assert.equal(hideGame.pawns.find(pawn => pawn.id === "thief-1").hidingTurns, 1);

const rescueGame = CityChase.createGame("p", "경찰");
CityChase.addPlayer(rescueGame, "t", "도둑");
assignSeats(rescueGame);
CityChase.startGame(rescueGame);
CityChase.placeSecrets(rescueGame, "p", { gems: ["market", "air"], undercover: "burger" });
rescueGame.pawns.filter(pawn => pawn.team === "police").forEach((pawn, index) => { pawn.position = `p${10 + index}`; });
const rescuer = rescueGame.pawns.find(pawn => pawn.id === "thief-1");
const captive = rescueGame.pawns.find(pawn => pawn.id === "thief-2");
rescuer.position = "p15";
captive.position = "jail";
captive.status = "jailed";
assert.equal(CityChase.roll(rescueGame, "t", 1).ok, true);
assert.equal(CityChase.moveStep(rescueGame, "t", "jail").ok, true);
assert.equal(rescueGame.pending.type, "rescue");
assert.equal(CityChase.choosePending(rescueGame, "t", "thief-2").ok, true);
assert.equal(rescuer.position, "hideout");
assert.equal(captive.position, "hideout");
assert.equal(captive.status, "active", "동료가 구금 구역으로 들어와 구출하면 두 도둑 모두 비밀기지로 돌아와야 합니다.");

const cardGame = CityChase.createGame("p", "경찰");
CityChase.addPlayer(cardGame, "t", "도둑");
assignSeats(cardGame);
CityChase.startGame(cardGame);
CityChase.placeSecrets(cardGame, "p", { gems: ["market", "air"], undercover: "burger" });
const trickNext = CityChase.BOARD.neighbors("p1", "police")[0].id;
assert.equal(CityChase.placeTrick(cardGame, "t", "p1", trickNext).ok, true);
assert.equal(cardGame.resources.thief.trickCards, 8);
cardGame.turnIndex = 3;
cardGame.turnMode = "awaiting_roll";
assert.equal(CityChase.placeCheck(cardGame, "p", "p2").ok, true);
assert.equal(cardGame.resources.police.checkCards, 5);

const captureGame = CityChase.createGame("p", "경찰");
CityChase.addPlayer(captureGame, "t", "도둑");
assignSeats(captureGame);
CityChase.startGame(captureGame);
CityChase.placeSecrets(captureGame, "p", { gems: ["market", "air"], undercover: "burger" });
const captureTarget = CityChase.BOARD.neighbors("p0", "police").find(item => item.id !== "hideout").id;
captureGame.pawns.find(pawn => pawn.id === "thief-1").position = captureTarget;
captureGame.pawns.find(pawn => pawn.id === "thief-2").status = "jailed";
captureGame.pawns.find(pawn => pawn.id === "thief-2").position = "jail";
captureGame.pawns.find(pawn => pawn.id === "thief-3").status = "jailed";
captureGame.pawns.find(pawn => pawn.id === "thief-3").position = "jail";
captureGame.pawns.find(pawn => pawn.id === "police-1").position = "p0";
captureGame.turnIndex = 3;
captureGame.turnMode = "awaiting_roll";
assert.equal(CityChase.roll(captureGame, "p", 1).ok, true);
assert.equal(CityChase.moveStep(captureGame, "p", captureTarget).ok, true);
assert.equal(captureGame.phase, "ended");
assert.equal(captureGame.winnerTeam, "police", "도둑 세 명을 모두 체포하면 경찰팀이 이겨야 합니다.");

const gemGame = CityChase.createGame("p", "경찰");
CityChase.addPlayer(gemGame, "t", "도둑");
assignSeats(gemGame);
CityChase.startGame(gemGame);
CityChase.placeSecrets(gemGame, "p", { gems: ["market", "air"], undercover: "burger" });
gemGame.resources.thief.securedGems = 1;
const runner = gemGame.pawns.find(pawn => pawn.id === "thief-1");
runner.position = "p0";
runner.carryingGem = true;
assert.equal(CityChase.roll(gemGame, "t", 1).ok, true);
assert.equal(CityChase.moveStep(gemGame, "t", "hideout").ok, true);
assert.equal(gemGame.phase, "ended");
assert.equal(gemGame.winnerTeam, "thief", "보석 두 개를 비밀기지로 옮기면 도둑팀이 이겨야 합니다.");

const html = fs.readFileSync(path.resolve(__dirname, "..", "learning", "games", "citychase", "citychase.html"), "utf8");
const css = fs.readFileSync(path.resolve(__dirname, "..", "learning", "games", "citychase", "citychase.css"), "utf8");
const client = fs.readFileSync(path.resolve(__dirname, "..", "learning", "games", "citychase", "citychase.js"), "utf8");
const server = fs.readFileSync(path.resolve(__dirname, "..", "game-hub-server", "server.js"), "utf8");
assert.match(html, /id="boardCanvas"/);
assert.match(html, /id="roomCode"/);
assert.match(client, /allowedPlayerCounts:\s*\[2,\s*3,\s*4,\s*5,\s*6\]/);
assert.match(client, /CITYCHASE_ACTION/);
assert.match(css, /min-height:\s*44px/);
assert.match(css, /city-board-v8\.png/, "축소된 비밀기지·구금 구역·상가 부지가 있는 정상 방향의 최종 배경을 사용해야 합니다.");
assert.doesNotMatch(css, /transform:\s*rotate\(180deg\)/, "배경 전체를 뒤집어 캐릭터 방향을 바꾸면 안 됩니다.");
assert.match(client, /도둑팀 비밀기지[\s\S]*경찰팀 구금 구역/, "두 시작 구역은 그림 추측이 아니라 실제 이름판으로 표시해야 합니다.");
assert.match(css, /\.node::after\s*\{[^}]*inset:\s*-11px/s, "작은 보드 칸에도 44px 이상의 터치 영역이 필요합니다.");
assert.match(client, /lineWidth = isRail \? 14/, "실제 이동 칸은 굵은 보드게임 경로로 연결되어야 합니다.");
assert.match(css, /width: 54px;\s*\n\s*height: 54px;/, "플레이어 말은 배경 시민보다 확실히 크게 보여야 합니다.");
assert.match(css, /width: clamp\(70px, 6vw, 90px\)/, "상가 말은 축소된 부지 안에 들어가야 합니다.");
assert.match(client, /building-plot\.png[\s\S]*shop-building\.png/, "상가 말은 빈 부지와 설치된 건물 그림을 분리해 보여줘야 합니다.");
assert.match(client, /node\.kind === "building" \? "입구"/, "건물에 들어가는 실제 칸은 입구라고 명확히 표시해야 합니다.");
assert.match(client, /secret-gem\.png[\s\S]*secret-alarm\.png/, "보석과 경보 장치는 전용 그림 자산을 사용해야 합니다.");
assert.match(client, /function playSfx[\s\S]*ClassGameSfx[\s\S]*function showBoardEffect/, "중요 사건은 시각효과와 사이트 공용 효과음을 함께 사용해야 합니다.");
assert.match(css, /height: 100dvh; min-height: 0; overflow: hidden/, "가로 화면에서는 게임 전체가 뷰포트 안에 고정되어야 합니다.");
assert.match(css, /width: min\(100%, calc\(\(100dvh - 93px\) \* 1\.5625\)\)/, "보드 크기는 남은 화면 높이를 넘지 않아야 합니다.");
assert.doesNotMatch(css, /min-width:\s*(?:820|900)px/, "Chromebook과 iPad에서 보드가 강제로 잘리면 안 됩니다.");
assert.match(css, /\.boardViewport[^}]*place-items: center[^}]*overflow: hidden/s, "가로 화면 보드는 스크롤 없이 전체가 보여야 합니다.");
assert.match(css, /\.boardPanel \{ height: auto; aspect-ratio: 1000 \/ 640; \}/, "iPad 세로 화면에서도 보드 전체 비율을 유지해야 합니다.");
assert.match(css, /@media\s*\(orientation:\s*portrait\),\s*\(max-width:\s*820px\)/);
assert.match(html, /class="lobbyWorkspace"/, "대기 화면은 접속과 참가자 상태를 한눈에 보여줘야 합니다.");
assert.match(html, /id="lobbyScreen"[^>]*data-multiplayer-lobby/, "대기실은 사이트 공통 멀티플레이 UI 규칙을 사용해야 합니다.");
assert.doesNotMatch(html, /각자의 기기로 참가/, "대기실 제목줄에 접속 방식을 중복 설명하면 안 됩니다.");
assert.match(css, /\.lobbyTop \{ display: grid; grid-template-columns: minmax\(0, 1fr\) auto minmax\(230px, 320px\)/, "대기 화면의 주요 행동은 첫 화면에 보여야 합니다.");
assert.match(css, /\.lobbyWorkspace \{ display: grid; grid-template-columns: minmax\(240px, \.72fr\) minmax\(360px, 1\.28fr\)/, "Chromebook 가로 화면에서는 접속과 참가자 패널을 간결하게 나란히 보여야 합니다.");
assert.match(css, /\[data-multiplayer-lobby\] \.lobbyConnect \.mp-lobby-card[\s\S]*width: 100%; min-height: 0; margin: 0;[\s\S]*background: #fffdf5/s, "활성 접속 카드는 불투명한 밝은 패널로 읽기 쉽게 보여야 합니다.");
assert.match(css, /\.lobbyConnect \{ grid-column: 1; grid-row: 1; \}[\s\S]*\.playersPanel \{ grid-column: 2; grid-row: 1; \}[\s\S]*\.teamSeatPanel \{ grid-column: 1 \/ -1; grid-row: 2; \}/s, "접속 정보와 참가자는 같은 줄에, 팀 슬롯은 그 아래 전체 폭에 배치해야 합니다.");
assert.match(css, /\.teamSeat:disabled \{ cursor: not-allowed; opacity: 1; \}/, "잠긴 팀 슬롯도 안내 문구를 선명하게 읽을 수 있어야 합니다.");
assert.match(css, /@media \(max-width: 900px\)[\s\S]*\.lobbyWorkspace \{ grid-template-columns: 1fr; \}/, "iPad 세로 화면에서는 대기 패널을 한 열로 배치해야 합니다.");
assert.match(client, /function avatarOf\(playerId\)/, "학생 아바타는 멀티플레이 대기실 정보에서 가져와야 합니다.");
assert.match(css, /lobby-city\.jpg/, "제공한 도심 그림을 대기실 전용 배경으로 사용해야 합니다.");
assert.match(html, /경찰과 도둑/, "공개 제목은 한국어 이름인 경찰과 도둑을 사용해야 합니다.");
assert.match(html, /COPS AND ROBBERS/i, "공개 제목은 영어 이름을 함께 병기해야 합니다.");
assert.doesNotMatch(html, /도둑잡기|잠복경찰|속임수 카드|검문 카드/, "공개 화면에 원작을 특정하는 명칭과 설명서식 용어가 남으면 안 됩니다.");
assert.doesNotMatch(server, /도둑잡기|잠복경찰|속임수 카드|검문 카드/, "서버 안내 문구도 독자적인 용어를 사용해야 합니다.");
assert.match(html, /가짜 단서 카드/, "도둑팀의 유도 카드는 학생이 기능을 바로 이해할 수 있는 이름을 사용해야 합니다.");
assert.doesNotMatch(html + client + server, /방향 표지/, "모호한 방향 표지 명칭이 공개 안내에 남으면 안 됩니다.");
assert.match(css, /\.lobbyShell::before[\s\S]*linear-gradient\(#ffffff18, #ffffff18\)[\s\S]*cover[\s\S]*filter: none/s, "대기실 배경은 과도하게 흐리거나 탈색하지 않고 원본 선명도를 유지해야 합니다.");
assert.match(client, /pawnName[\s\S]*pawnFaceMarkup\(controllers\)[\s\S]*pawnNumber/, "말에는 학생 이름·아바타·말 번호가 함께 보여야 합니다.");
assert.match(html, /id="policeSeatSlots"[\s\S]*id="thiefSeatSlots"/, "대기실에는 경찰팀·도둑팀 슬롯이 모두 있어야 합니다.");
assert.match(client, /sendAction\("CHOOSE_SEAT"/, "학생은 빈 슬롯을 눌러 자기 팀 자리를 선택해야 합니다.");
assert.match(client, /canStart:\s*\(\)\s*=>\s*!!state\?\.lobbyReady/, "공용 시작 버튼도 팀 슬롯 완료 상태를 확인해야 합니다.");
assert.match(client, /말 1 \+ 말 3 공동[\s\S]*말 2 \+ 말 3 공동/, "2인 팀은 세 번째 말을 공동으로 맡는다고 안내해야 합니다.");
assert.match(server, /action === "CHOOSE_SEAT"/, "팀 슬롯 선택은 서버 권한 상태로 동기화해야 합니다.");
assert.match(css, /--police: #2374cc/, "경찰 말은 명확한 파란색이어야 합니다.");
assert.match(css, /--thief: #e9475f/, "도둑 말은 명확한 빨간색이어야 합니다.");
assert.match(client, /class="secretIcon gemIcon"/, "보석은 문자 기호 대신 선명한 전용 이미지 배지를 사용해야 합니다.");
assert.match(client, /class="secretIcon undercoverIcon"/, "경보 장치는 문자 기호 대신 선명한 전용 이미지 배지를 사용해야 합니다.");
assert.match(css, /\.pawn:disabled \{ opacity: 1; \}/, "대기 중인 플레이어 말도 흐려지지 않아야 합니다.");
assert.match(css, /\.pawn\.carrying::after[\s\S]*secret-gem\.png/, "말이 든 보석도 선명한 전용 이미지 배지로 보여야 합니다.");
assert.match(server, /citychase:\s*6/);
assert.match(server, /CITYCHASE_ACTION/);
assert.match(server, /CityChase\.stateFor/);

console.log("citychase-unit: board, secrecy, movement, cards, capture, gem victory and responsive contract ok");
