(() => {
    "use strict";

    // 시집 차례표. 시 본문은 poems/<아이디>.js, 목록 화면용 요약은 poems-index.js에 있고
    // 여기서는 시집 한 권에 시 몇 편이 실리는지만 묶는다.
    // 학년 표시는 두지 않는다 — 실제 교과서 목차를 확인한 것이 아니라 난이도로만 순서를 매겼다.
    // 배열에 적힌 차례가 곧 "차례대로 읽기"의 순서다.
    // title은 이 시집에 실린 시들의 공통된 특징을 담은 짧은 제목이다(시 개별 제목과는 다르다).
    const book = (id, title, poemIds) => ({ id, title, poemIds });

    window.POETRY_BOOKS = Object.freeze([
        book("g3-scene", "그림 같은 장면",
            ["jiyong-hosu", "jiyong-byeoltong", "taeeung-gamjakkot", "jiyong-hongsi"]),
        book("g3-repeat", "되풀이하는 노래",
            ["sowol-eommaya", "sowol-geumjandi", "deokchul-bompyeonji", "dongju-banditbul"]),
        book("g3-mimetic", "소리와 모습을 담은 말",
            ["dongju-haetbi", "dongju-chamsae", "jiyong-hongsi"]),
        book("g3-calling", "말을 건네는 시",
            ["folk-saeya", "folk-dara", "folk-dukkeobi", "sowol-eommaya"]),
        book("g3-asking", "묻는 말로 여는 시",
            ["rossetti-baram", "dongju-nun", "folk-eodikkaji"]),

        book("g4-simile", "무엇에 빗댄 시",
            ["stevenson-geurimja", "leejanghee-bomeun", "dongju-haetbi", "stevenson-bi"]),
        book("g4-persona", "사람처럼 움직이는 사물",
            ["dongju-bom", "dongju-jogaekkeopjil", "rossetti-baram", "deokchul-bompyeonji"]),
        book("g4-senses", "다섯 감각으로 그린 시",
            ["rossetti-bunhong", "leebaek-jeongyasa", "dubo-chunyahuiu", "stevenson-geune"]),
        book("g4-speaker", "시 속 사람의 자리",
            ["dongju-gulttuk", "kimyeongrang-omae", "jiyong-byeoltong", "dongju-jogaekkeopjil"]),
        book("g4-bittersweet", "웃음 뒤에 숨은 마음",
            ["dongju-ojumssagae", "dongju-geojitburi", "dongju-chamsae", "jiyong-hongsi"]),

        book("g5-metaphor", "은유로 말하는 시",
            ["manhae-narutbae", "dongju-sonyeon", "dongju-nun", "leejanghee-bomeun"]),
        book("g5-sound", "부드러운 소리와 센 소리",
            ["yeongrang-doldam", "dongju-bom", "kimyeongrang-omae", "dongju-haetbi"]),
        book("g5-empathy", "마음을 옮겨 놓은 사물",
            ["wangbangyeon-cheonmalli", "leegae-chokbul", "dongju-jogaekkeopjil"]),
        book("g5-flow", "시가 흘러가는 길",
            ["sowol-sanyuhwa", "sowol-gaeyeoul", "dongju-saeroun-gil", "jiyong-byeoltong"]),
        book("g5-sijo", "석 줄에 담는 옛 노래",
            ["leesunsin-hansanseom", "yunseondo-ouga", "hwanghui-daechu", "leejeongbo-gukhwa"]),

        book("g6-irony", "어긋난 겉말과 속말",
            ["sowol-jindallae", "sowol-meonhuil", "sasol-dukkeobi"]),
        book("g6-paradox", "말이 안 되어도 통하는 뜻",
            ["manhae-bokjong", "manhae-alsu", "manhae-narutbae"]),
        book("g6-symbol", "별 하나에 담은 뜻",
            ["dongju-seosi", "yuksa-cheongpodo", "nocheonmyeong-saseum"]),
        book("g6-contrast", "빛깔과 처지를 나란히",
            ["dongju-jahwasang", "yuksa-cheongpodo", "sowol-sanyuhwa", "nocheonmyeong-saseum"]),
        book("g6-compare", "닮은 시와 다른 시",
            ["leebangwon-hayeoga", "jeongmongju-dansimga", "sowol-jindallae", "sowol-meonhuil"]),
        book("g6-oldsong", "가장 오래된 우리 노래들",
            ["goryeo-cheongsan", "goryeo-gasiri", "gojia-guji", "jiyong-hyangsu"]),

        // 여기서부터는 배우는 것이 아니라 시인으로 묶는다. 시험은 아는 시인의 처음 보는 시를 내니까,
        // 익숙한 시 곁에 처음 보는 시를 한 편씩 두어 그 시인의 버릇을 익히게 한다.
        book("m1-jiyong", "아는 시인, 처음 보는 시",
            ["jiyong-yurichang", "jiyong-hyangsu", "jiyong-hosu", "jiyong-byeoltong"]),
        book("m1-sowol", "헤어짐 앞에서 머뭇거리는 시",
            ["sowol-ganeungil", "sowol-jeopdongsae", "sowol-jindallae", "sowol-sanyuhwa"]),
        book("m1-era", "시대를 담은 시",
            ["sanghwa-ppaeatgin", "yuksa-cheongpodo", "dongju-seosi"]),
        book("m1-hyangga", "신라 향가 세 편",
            ["hyangga-jemangmaega", "hyangga-seodongyo", "hyangga-heonhwaga"]),
        book("m1-textbook", "그리운 것을 향한 마음",
            ["gihyeongdo-eomma", "kimjonggil-seongtanje", "sinseokjeong-meonnara"]),

        book("m2-manhae", "어긋난 말에 담은 님",
            ["manhae-nim", "manhae-narutbae", "manhae-bokjong", "manhae-alsu"]),
        book("m2-yuksa", "벼랑 끝에서 세운 뜻",
            ["yuksa-jeoljeong", "yuksa-kkot", "yuksa-cheongpodo"]),
        book("m2-yeongrang", "찬란한 슬픔의 봄",
            ["yeongrang-moran", "yeongrang-doldam", "kimyeongrang-omae"]),
        book("m2-dongju", "나를 들여다보는 시",
            ["dongju-ttodareun", "dongju-jahwasang", "dongju-seosi"]),
        book("m2-leaving", "문턱에서 머뭇거리는 시",
            ["ojanghwan-gohyang", "yongcheol-tteonaganeun"]),
        book("m2-old", "시조 세 수와 고려 노래 둘",
            ["leehwang-dosan", "goryeo-dongdong", "goryeo-jeongseokga"]),

        book("m3-yuksa", "시간을 펼쳐 놓은 뜻",
            ["yuksa-gwangya", "yuksa-gyomok", "yuksa-jeoljeong"]),
        book("m3-dongju", "거울을 닦는 시",
            ["dongju-chamhoerok", "dongju-sipjaga", "dongju-swipge", "dongju-seosi"]),
        book("m3-sowol", "눌러 참기와 목놓아 부르기",
            ["sowol-chohon", "sowol-sakju", "sowol-jindallae"]),
        book("m3-modern", "가까운 것이 낯설어질 때",
            ["leesang-geoul", "jiyong-gohyang", "inhwan-sewol"]),
        book("m3-river", "흐르는 물에 얹은 뜻과 눈물",
            ["yeongro-nongae", "jisang-songin", "wangbangyeon-cheonmalli"]),
        book("m3-gasa", "길게 이어지는 옛 노래글",
            ["geugin-sangchun", "seondo-eobu", "jeongcheol-gwandong"]),

        book("h1-jiyong", "감정을 지운 자리",
            ["jiyong-bi", "jiyong-indongcha", "jiyong-jangsusan", "jiyong-yurichang"]),
        book("h1-two-faces", "아는 이름의 낯선 시",
            ["yeongrang-dok", "yeongrang-buk", "yuksa-jayagok", "yeongrang-doldam"]),
        book("h1-dongju", "담 저쪽의 나",
            ["dongju-gil", "dongju-gan", "dongju-chamhoerok"]),
        book("h1-leesang", "띄어쓰기를 없앤 까닭",
            ["leesang-ogamdo", "leesang-geoul"]),
        book("h1-hyangga", "열 줄 노래의 짜임",
            ["hyangga-changiparang", "hyangga-anminga", "hyangga-jemangmaega"]),
        book("h1-joseon", "나라의 노래와 한 사람의 노래",
            ["joseon-yongbi", "jeongcheol-samiin"]),
        book("h1-textbook", "잃은 것 앞에서",
            ["baekseok-yeoseung", "hyeonseung-platanus", "gwangseop-bidulgi", "hyeonggi-nakhwa"]),

        book("h2-gwandong", "금강산·동해·꿈",
            ["jeongcheol-gwandong-2", "jeongcheol-gwandong"]),
        book("h2-songmiin", "두 여인의 대화",
            ["jeongcheol-songmiin", "jeongcheol-samiin"]),
        book("h2-gyuwon", "여인이 쓴 여인의 노래",
            ["heo-gyuwonga", "jeongcheol-samiin"]),
        book("h2-nuhang", "전쟁 뒤의 가사",
            ["bakinro-nuhangsa", "bakinro-seonsangtan"]),
        book("h2-nongga", "열두 달 농사 노래",
            ["jeonghakyu-nongga", "goryeo-dongdong"]),
        book("h2-sijo-1", "산에 살아도 마음은 임금께",
            ["leei-gosan", "seondo-manheung", "seondo-gyeonhoeyo"]),
        book("h2-sijo-2", "매화와 국화, 그리고 두꺼비",
            ["minyeong-maehwasa", "leejeongbo-gukhwa", "sasol-dukkeobi"]),
        book("h2-goryeo", "이별의 세 목소리",
            ["goryeo-seogyeong", "goryeo-manjeonchun", "jeongseo-jeonggwajeong", "goryeo-gasiri"]),
        book("h2-hansi", "참새와 황두, 텅 빈 성과 무궁화",
            ["jehyeon-sarihwa", "leesaek-bubyeongnu", "hwanghyeon-jeolmyeong", "dasan-tamjin"]),
        book("h2-minyo", "지은이 없는 노래들",
            ["folk-sijipsari", "japga-yusanga", "goryeo-cheongsan"]),

        book("h2-m-north", "고향과 가족을 그리는 마음",
            ["baekseok-yeounangol", "baekseok-namsinuiju", "baekseok-huinbaram", "yongak-nalgeunjip"]),
        book("h2-m-image", "이미지로 그린 마음",
            ["gwanggyun-wasadeung", "gwanggyun-chuil", "chihwan-gitbal", "chihwan-saengmyeong"]),
        book("h2-m-cheongrok", "자연에 기댄 마음",
            ["mogwol-nageune", "jihun-seungmu", "dujin-hae", "jeongju-gukhwa", "jeongju-chucheonsa"]),
        book("h2-m-sixties", "맞서는 마음",
            ["suyeong-pul", "suyeong-nun", "suyeong-pokpo", "suyeong-gogung", "dongyeop-kkeopdegi"]),
        book("h2-m-being", "존재를 묻는 시",
            ["chunsu-kkot", "chunsu-seosi", "sangbyeong-gwicheon", "donggyu-pyeonji"]),
        book("h2-m-life", "삶의 애환을 담은 시",
            ["gyeongnim-nongmu", "jaesam-chueok", "jaesam-gaeulgang", "jaegu-sapyeong", "gihyeongdo-binjip"])
    ]);
})();
