const places={
  gyeongbokgung:{name:"경복궁",region:"서울특별시",type:"문화유산",latitude:37.5796,longitude:126.9770,elementary:"조선 시대 왕이 생활하고 나라의 중요한 일을 처리하던 궁궐이에요. 넓은 마당과 여러 전각을 살펴보며 조선의 궁궐 생활을 상상해 볼 수 있어요.",middle:"경복궁은 조선 왕조의 법궁으로 건립된 궁궐입니다. 공간의 배치와 전각의 역할을 살펴보면 조선의 통치 질서와 궁궐 건축의 특징을 이해할 수 있습니다.",mission:"근정전과 경회루의 쓰임이 어떻게 달랐을지 건물의 위치와 모습을 보고 추리해 보세요."},
  gongju:{name:"공산성",region:"충청남도 공주시",type:"역사 유적",latitude:36.4624,longitude:127.1282,elementary:"백제 사람들이 왕성과 마을을 지키기 위해 쌓은 성이에요. 성곽길을 따라 걸으며 강과 산을 어떻게 이용했는지 살펴볼 수 있어요.",middle:"공산성은 백제 웅진 시기의 왕성으로 알려진 산성입니다. 금강과 주변 지형을 활용한 방어 구조에서 당시 도읍의 입지 조건을 살펴볼 수 있습니다.",mission:"성에서 금강이 보이는 방향을 찾고, 이 위치가 방어에 어떤 도움을 주었을지 설명해 보세요."},
  bulguksa:{name:"불국사",region:"경상북도 경주시",type:"문화유산",latitude:35.7900,longitude:129.3320,elementary:"신라 사람들이 바라는 아름다운 불교 세계를 건물과 돌계단으로 표현한 절이에요. 석가탑과 다보탑의 서로 다른 모습을 비교해 보세요.",middle:"불국사는 통일 신라의 불교 문화와 건축 기술을 보여주는 사찰입니다. 건물·석축·탑의 배치를 통해 당시의 종교관과 미적 감각을 탐구할 수 있습니다.",mission:"석가탑과 다보탑에서 서로 다른 모양을 세 가지 찾아 기록해 보세요."},
  suncheon:{name:"순천만",region:"전라남도 순천시",type:"생태 탐방",latitude:34.8855,longitude:127.5090,elementary:"바닷물과 강물이 만나는 곳에 넓은 갯벌과 갈대밭이 펼쳐져 있어요. 다양한 새와 작은 생물이 함께 살아가는 모습을 관찰할 수 있어요.",middle:"순천만은 갯벌과 염습지, 갈대 군락이 이어지는 연안 습지입니다. 생물 다양성과 습지가 환경에 미치는 역할을 현장에서 살펴볼 수 있습니다.",mission:"갈대밭과 갯벌에서 발견한 생물의 흔적을 각각 하나씩 찾아보세요."},
  seongsan:{name:"성산일출봉",region:"제주특별자치도",type:"자연 지형",latitude:33.4581,longitude:126.9425,elementary:"바닷속 화산이 폭발하며 만들어진 커다란 봉우리예요. 정상의 둥근 분화구와 주변 바다를 함께 관찰할 수 있어요.",middle:"성산일출봉은 바닷속 화산 활동으로 형성된 응회구입니다. 화산재가 쌓여 만들어진 지층과 침식 지형을 통해 제주도의 형성 과정을 탐구할 수 있습니다.",mission:"봉우리의 옆면에서 층처럼 보이는 부분을 찾아 화산 분출 당시의 모습을 상상해 보세요."}
};
const nodes={schoolSummary:document.querySelector("#schoolSummary"),originBadge:document.querySelector("#originBadge"),routeSchool:document.querySelector("#routeSchool"),routeStatus:document.querySelector("#routeStatus"),placeRegion:document.querySelector("#placeRegion"),placeName:document.querySelector("#placeName"),placeType:document.querySelector("#placeType"),routeDestination:document.querySelector("#routeDestination"),placeDescription:document.querySelector("#placeDescription"),placeMission:document.querySelector("#placeMission"),levelButton:document.querySelector("#levelButton")};
let membership=null,selectedKey="gyeongbokgung",middleLevel=false;
function distanceKm(lat1,lon1,lat2,lon2){const rad=value=>value*Math.PI/180,earth=6371,dLat=rad(lat2-lat1),dLon=rad(lon2-lon1);const a=Math.sin(dLat/2)**2+Math.cos(rad(lat1))*Math.cos(rad(lat2))*Math.sin(dLon/2)**2;return earth*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));}
function renderRoute(place){const schoolName=membership?.schoolName||"등록된 학교 없음";nodes.routeSchool.textContent=schoolName;nodes.originBadge.textContent=membership?.schoolName?`출발 · ${membership.schoolName}`:"출발지 미등록";if(Number.isFinite(membership?.schoolLatitude)&&Number.isFinite(membership?.schoolLongitude)){const km=distanceKm(membership.schoolLatitude,membership.schoolLongitude,place.latitude,place.longitude);nodes.routeStatus.textContent=`직선거리 약 ${Math.round(km)}km · 실제 경로와 예상 시간은 길찾기 연결 후 표시됩니다.`;}else{nodes.routeStatus.textContent="학교의 정확한 위치가 등록되면 실제 경로와 예상 시간을 확인할 수 있어요.";}}
function renderPlace(){const place=places[selectedKey];nodes.placeRegion.textContent=place.region;nodes.placeName.textContent=place.name;nodes.placeType.textContent=place.type;nodes.routeDestination.textContent=place.name;nodes.placeDescription.textContent=middleLevel?place.middle:place.elementary;nodes.placeMission.textContent=place.mission;renderRoute(place);}
document.querySelectorAll(".place-pin").forEach(button=>button.addEventListener("click",()=>{selectedKey=button.dataset.place;document.querySelectorAll(".place-pin").forEach(pin=>pin.classList.toggle("is-selected",pin===button));renderPlace();}));
nodes.levelButton.addEventListener("click",()=>{middleLevel=!middleLevel;nodes.levelButton.textContent=middleLevel?"중등 설명":"초등 설명";nodes.levelButton.setAttribute("aria-pressed",String(middleLevel));renderPlace();});
async function loadMembership(){try{const response=await fetch("/api/auth/me",{headers:{Accept:"application/json"}});if(!response.ok)throw new Error("AUTH_REQUEST_FAILED");const state=await response.json();membership=state.membership||null;nodes.schoolSummary.textContent=membership?.schoolName?`${membership.schoolName}에서 출발하는 여행을 준비해요.`:"학교 소속을 등록하면 우리 학교에서 출발할 수 있어요.";}catch(_){nodes.schoolSummary.textContent="학교 정보를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.";}renderPlace();}
renderPlace();loadMembership();