window.KOREA_TRAVEL_PLACES.push(...[
  {
    "id": "value-대한민국역사박물관",
    "name": "대한민국역사박물관",
    "region": "서울특별시 종로구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.5739553,
    "lng": 126.9778057,
    "description": "대한민국역사박물관에서는 근현대 생활과 민주주의, 산업화의 변화를 실물 자료와 기록으로 비교하는 전시에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://www.much.go.kr/"
  },
  {
    "id": "value-서울역사박물관",
    "name": "서울역사박물관",
    "region": "서울특별시 종로구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.5704789,
    "lng": 126.9705257,
    "description": "서울역사박물관에서는 서울이 성장하며 집·교통·생활공간이 변한 과정을 보여주는 도시사 전시에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://museum.seoul.go.kr/"
  },
  {
    "id": "value-부산박물관",
    "name": "부산박물관",
    "region": "부산광역시 남구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 35.1293619,
    "lng": 129.0942026,
    "description": "부산박물관에서는 선사시대부터 현대까지 부산 지역의 역사와 해양 교류를 보여주는 유물에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://museum.busan.go.kr/busan/"
  },
  {
    "id": "value-부산어촌민속관",
    "name": "부산어촌민속관",
    "region": "부산광역시 북구",
    "category": "career",
    "categoryName": "직업·생활",
    "emoji": "🧰",
    "lat": 35.233796,
    "lng": 129.0085352,
    "description": "부산어촌민속관에서는 낙동강과 바다의 어업 도구, 어촌 생활과 물고기 잡는 기술에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "체험별 이용 조건 확인",
    "reservation": "개인 체험 프로그램 사전예약 확인",
    "officialUrl": "https://www.busan.go.kr/fisheriesmuseum/"
  },
  {
    "id": "value-대구근대역사관",
    "name": "대구근대역사관",
    "region": "대구광역시 중구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 35.8717633,
    "lng": 128.5911236,
    "description": "대구근대역사관에서는 근대 대구의 거리·교육·산업·시민 생활 변화를 보여주는 자료에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://daeguartscenter.or.kr/dmhm/"
  },
  {
    "id": "value-도동서원",
    "name": "도동서원",
    "region": "대구광역시 달성군",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 35.7009217,
    "lng": 128.3719049,
    "description": "도동서원에서는 서원의 공간 배치와 조선시대 교육·제례 문화를 살펴보는 세계유산에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://www.dalseong.daegu.kr/tour/"
  },
  {
    "id": "value-강화역사박물관",
    "name": "강화역사박물관",
    "region": "인천광역시 강화군",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.7723072,
    "lng": 126.4365264,
    "description": "강화역사박물관에서는 선사시대부터 고려와 근현대까지 강화도의 역사를 잇는 유물에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://www.ganghwa.go.kr/open_content/museum/"
  },
  {
    "id": "value-대전시립박물관",
    "name": "대전시립박물관",
    "region": "대전광역시 유성구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 36.338361,
    "lng": 127.335044,
    "description": "대전시립박물관에서는 대전의 역사와 교통도시 성장 과정을 지역 자료로 살펴보는 박물관에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://www.daejeon.go.kr/his/"
  },
  {
    "id": "value-국립대전현충원",
    "name": "국립대전현충원",
    "region": "대전광역시 유성구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 36.3704985,
    "lng": 127.2931521,
    "description": "국립대전현충원에서는 나라를 위해 헌신한 사람들의 기록을 통해 역사와 공동체 책임을 생각하는 공간에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://www.dnc.go.kr/"
  },
  {
    "id": "value-울산박물관",
    "name": "울산박물관",
    "region": "울산광역시 남구",
    "category": "career",
    "categoryName": "직업·생활",
    "emoji": "🧰",
    "lat": 35.5272651,
    "lng": 129.308711,
    "description": "울산박물관에서는 선사문화부터 자동차·조선·석유화학 산업도시의 성장까지 잇는 전시에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "체험별 이용 조건 확인",
    "reservation": "개인 체험 프로그램 사전예약 확인",
    "officialUrl": "https://www.ulsan.go.kr/s/museum/"
  },
  {
    "id": "value-세종전통문화체험관",
    "name": "세종전통문화체험관",
    "region": "세종특별자치시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 36.5065984,
    "lng": 127.2916478,
    "description": "세종전통문화체험관에서는 한옥과 공예, 세시풍속을 직접 경험하며 전통생활을 이해하는 체험에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://www.sejong.go.kr/tour/"
  },
  {
    "id": "value-국립현대미술관-과천",
    "name": "국립현대미술관 과천",
    "region": "경기도 과천시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.4309964,
    "lng": 127.0196745,
    "description": "국립현대미술관 과천에서는 현대미술 작품의 재료와 표현 방법을 관찰하고 생각을 말로 풀어보는 미술관에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://www.mmca.go.kr/"
  },
  {
    "id": "value-경기도박물관",
    "name": "경기도박물관",
    "region": "경기도 용인시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.2670047,
    "lng": 127.105228,
    "description": "경기도박물관에서는 경기도의 역사와 생활문화를 유물과 어린이 체험으로 연결한 박물관에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://musenet.ggcf.kr/"
  },
  {
    "id": "value-남한산성",
    "name": "남한산성",
    "region": "경기도 광주시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.4791368,
    "lng": 127.1801588,
    "description": "남한산성에서는 산성의 지형과 성벽, 방어시설을 통해 조선시대 수도 방어를 이해하는 유적에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://www.gg.go.kr/namhansansung-2/"
  },
  {
    "id": "value-실학박물관",
    "name": "실학박물관",
    "region": "경기도 남양주시",
    "category": "science",
    "categoryName": "과학·진로",
    "emoji": "🔬",
    "lat": 37.5159848,
    "lng": 127.3005829,
    "description": "실학박물관에서는 생활을 개선하려 했던 실학자의 생각과 지도·천문·농업 지식을 잇는 전시에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내 전시·야외 일정 확인",
    "reservation": "체험 프로그램·운영시간 확인",
    "officialUrl": "https://silhak.ggcf.kr/"
  },
  {
    "id": "value-전곡선사박물관",
    "name": "전곡선사박물관",
    "region": "경기도 연천군",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 38.0115717,
    "lng": 127.0638467,
    "description": "전곡선사박물관에서는 석기 제작과 인류 진화, 선사인의 생활을 체험으로 이해하는 박물관에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://jgpm.ggcf.kr/"
  },
  {
    "id": "value-백남준아트센터",
    "name": "백남준아트센터",
    "region": "경기도 용인시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.2691184,
    "lng": 127.1105675,
    "description": "백남준아트센터에서는 텔레비전과 영상·소리·기술을 예술로 바꾼 미디어아트 작품에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://njp.ggcf.kr/"
  },
  {
    "id": "value-설악산국립공원",
    "name": "설악산국립공원",
    "region": "강원특별자치도 속초시",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 38.1729704,
    "lng": 128.4924735,
    "description": "설악산국립공원에서는 높이에 따라 달라지는 산지 지형과 식생, 계곡 생태를 관찰하는 국립공원에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "서로 다른 환경 두 곳을 골라 지형과 생물의 차이를 관찰하고 이유를 설명해 보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 개방 확인",
    "reservation": "탐방 예약·안전 안내 확인",
    "officialUrl": "https://www.knps.or.kr/"
  },
  {
    "id": "value-dmz박물관",
    "name": "DMZ박물관",
    "region": "강원특별자치도 고성군",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 38.5763824,
    "lng": 128.3827044,
    "description": "DMZ박물관에서는 분단의 역사와 비무장지대의 생태를 함께 살펴보는 박물관에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://www.dmzmuseum.com/"
  },
  {
    "id": "value-국립춘천박물관",
    "name": "국립춘천박물관",
    "region": "강원특별자치도 춘천시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.8637672,
    "lng": 127.7539316,
    "description": "국립춘천박물관에서는 강원 지역의 선사문화와 불교미술, 산과 강의 생활사를 보여주는 유물에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://chuncheon.museum.go.kr/"
  },
  {
    "id": "value-고성-통일전망대",
    "name": "고성 통일전망대",
    "region": "강원특별자치도 고성군",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 38.5867148,
    "lng": 128.3754599,
    "description": "고성 통일전망대에서는 북한 지역의 지형을 직접 바라보며 분단과 평화를 생각하는 전망 공간에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://www.tongiltour.co.kr/"
  },
  {
    "id": "value-국립청주박물관",
    "name": "국립청주박물관",
    "region": "충청북도 청주시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 36.6492486,
    "lng": 127.5120937,
    "description": "국립청주박물관에서는 충북 지역의 선사문화와 불교미술, 생활유물을 보여주는 박물관에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://cheongju.museum.go.kr/"
  },
  {
    "id": "value-국립현대미술관-청주",
    "name": "국립현대미술관 청주",
    "region": "충청북도 청주시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 36.65532,
    "lng": 127.4900794,
    "description": "국립현대미술관 청주에서는 보이는 수장고와 보존과학을 통해 미술품을 관리하는 과정을 살펴보는 미술관에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://www.mmca.go.kr/"
  },
  {
    "id": "value-의림지역사박물관",
    "name": "의림지역사박물관",
    "region": "충청북도 제천시",
    "category": "career",
    "categoryName": "직업·생활",
    "emoji": "🧰",
    "lat": 37.1760916,
    "lng": 128.2095091,
    "description": "의림지역사박물관에서는 오래된 저수지 의림지와 농업용수, 제천 사람들의 생활을 연결한 전시에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "체험별 이용 조건 확인",
    "reservation": "개인 체험 프로그램 사전예약 확인",
    "officialUrl": "https://www.jecheon.go.kr/museum/"
  },
  {
    "id": "value-공산성",
    "name": "공산성",
    "region": "충청남도 공주시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 36.4631426,
    "lng": 127.1264411,
    "description": "공산성에서는 금강과 산지 지형을 이용한 백제 왕성의 방어 구조를 살펴보는 세계유산에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://www.gongju.go.kr/tour/"
  },
  {
    "id": "value-국립부여박물관",
    "name": "국립부여박물관",
    "region": "충청남도 부여군",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 36.2763114,
    "lng": 126.919051,
    "description": "국립부여박물관에서는 백제의 금속공예와 불교문화, 사비도성의 생활을 보여주는 유물에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://buyeo.museum.go.kr/"
  },
  {
    "id": "value-국립전주박물관",
    "name": "국립전주박물관",
    "region": "전북특별자치도 전주시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 35.801028,
    "lng": 127.089704,
    "description": "국립전주박물관에서는 전북 지역의 역사와 전통문화, 기록유산을 살펴보는 박물관에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://jeonju.museum.go.kr/"
  },
  {
    "id": "value-국립나주박물관",
    "name": "국립나주박물관",
    "region": "전라남도 나주시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 34.9148163,
    "lng": 126.658967,
    "description": "국립나주박물관에서는 영산강 유역 마한 사람들의 무덤과 생활, 교류를 보여주는 유물에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://naju.museum.go.kr/"
  },
  {
    "id": "value-목포근대역사관",
    "name": "목포근대역사관",
    "region": "전라남도 목포시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 34.7875085,
    "lng": 126.3820779,
    "description": "목포근대역사관에서는 개항장 목포의 건물과 항구·철도·시민 생활 변화를 보여주는 전시에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://www.mokpo.go.kr/tour/"
  },
  {
    "id": "value-전남도립미술관",
    "name": "전남도립미술관",
    "region": "전라남도 광양시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 34.9677293,
    "lng": 127.5889345,
    "description": "전남도립미술관에서는 남도의 자연과 삶을 다양한 재료와 시각으로 표현한 현대미술에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://artmuseum.jeonnam.go.kr/"
  },
  {
    "id": "value-국립제주박물관",
    "name": "국립제주박물관",
    "region": "제주특별자치도 제주시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 33.5135053,
    "lng": 126.5486899,
    "description": "국립제주박물관에서는 제주의 선사문화와 탐라, 바다 교류의 역사를 보여주는 유물에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·체험·운영시간 확인",
    "officialUrl": "https://jeju.museum.go.kr/"
  },
  {
    "id": "value-한라산국립공원",
    "name": "한라산국립공원",
    "region": "제주특별자치도 제주시",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 33.3922451,
    "lng": 126.4942816,
    "description": "한라산국립공원에서는 화산섬의 고도별 지형과 식생, 계절 변화를 관찰하는 국립공원에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "서로 다른 환경 두 곳을 골라 지형과 생물의 차이를 관찰하고 이유를 설명해 보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 개방 확인",
    "reservation": "탐방 예약·안전 안내 확인",
    "officialUrl": "https://www.jeju.go.kr/hallasan/"
  },
  {
    "id": "value-고양어린이박물관",
    "name": "고양어린이박물관",
    "region": "경기도 고양시",
    "category": "career",
    "categoryName": "직업·생활",
    "emoji": "🧰",
    "lat": 37.6294458,
    "lng": 126.8310388,
    "description": "고양어린이박물관에서는 도시·환경·예술·신체를 놀이와 조작으로 탐구하는 어린이 체험관에 관한 내용을 구체적으로 살펴볼 수 있어요. 현장에서 근거를 찾고 서로 비교하면서 교과서의 개념을 실제 장소와 연결할 수 있어요.",
    "mission": "가장 인상적인 자료나 공간 하나를 골라 무엇을 알게 되었는지 근거 세 가지와 함께 기록해 보세요.",
    "season": "사계절",
    "weather": "체험별 이용 조건 확인",
    "reservation": "개인 체험 프로그램 사전예약 확인",
    "officialUrl": "https://www.goyangcm.or.kr/"
  }
]);
