window.KOREA_TRAVEL_PLACES.push(...[
  {
    "id": "gyeongbokgung",
    "name": "경복궁",
    "region": "서울특별시 종로구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.579754,
    "lng": 126.9766818,
    "description": "경복궁에서는 근정전과 경회루, 궁궐의 중심축과 조선 왕실 공간을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "문과 마당을 지나며 공간의 쓰임이 어떻게 달라지는지 세 곳을 골라 기록해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://royal.khs.go.kr/ROYAL/contents/R701000000.do"
  },
  {
    "id": "changdeokgung",
    "name": "창덕궁",
    "region": "서울특별시 종로구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.5823872,
    "lng": 126.9917013,
    "description": "창덕궁에서는 자연 지형을 살린 궁궐 배치와 후원의 건축을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "건물이 산과 나무의 모양에 맞춰 배치된 곳을 찾아 까닭을 생각해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://royal.khs.go.kr/ROYAL/contents/R702000000.do"
  },
  {
    "id": "national-museum-korea",
    "name": "국립중앙박물관",
    "region": "서울특별시 용산구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.523953,
    "lng": 126.9803196,
    "description": "국립중앙박물관에서는 선사시대부터 근현대까지 이어지는 대표 문화유산을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "서로 다른 시대의 생활도구 두 개를 골라 재료와 쓰임을 비교해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.museum.go.kr/"
  },
  {
    "id": "national-folk-museum",
    "name": "국립민속박물관",
    "region": "서울특별시 종로구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.5808343,
    "lng": 126.9790431,
    "description": "국립민속박물관에서는 옛사람의 집과 의식주, 세시풍속과 일생을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "오늘날에도 남아 있는 생활풍습 하나를 찾아 과거와 달라진 점을 적어 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.nfm.go.kr/"
  },
  {
    "id": "seodaemun-prison",
    "name": "서대문형무소역사관",
    "region": "서울특별시 서대문구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.5745368,
    "lng": 126.9563173,
    "description": "서대문형무소역사관에서는 독립운동가의 수감 생활과 자유·인권의 의미를 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "수감 기록 한 사람을 골라 그 사람이 지키려 했던 가치를 설명해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://sphh.sscmc.or.kr/"
  },
  {
    "id": "war-memorial",
    "name": "전쟁기념관",
    "region": "서울특별시 용산구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.5359715,
    "lng": 126.9772916,
    "description": "전쟁기념관에서는 전쟁의 원인과 피해, 평화를 지키기 위한 노력을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "전쟁을 기억하는 전시가 평화를 위해 필요한 이유를 자료 하나와 연결해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.warmemo.or.kr/"
  },
  {
    "id": "children-science-seoul",
    "name": "국립어린이과학관",
    "region": "서울특별시 종로구",
    "category": "science",
    "categoryName": "과학·진로",
    "emoji": "🔭",
    "lat": 37.5819473,
    "lng": 126.9973679,
    "description": "국립어린이과학관에서는 힘과 운동, 생명, 우주를 직접 조작하는 어린이 과학 체험을 직접 살펴볼 수 있어요. 직접 만지고 비교하며 교과서의 과학 원리를 실제 기술과 현상에 연결할 수 있어요.",
    "mission": "예상과 결과가 달랐던 전시를 찾아 무엇이 생각을 바꾸었는지 적어 보세요.",
    "season": "사계절",
    "weather": "실내 이용 가능",
    "reservation": "체험 회차 사전예약 확인",
    "officialUrl": "https://www.csc.go.kr/"
  },
  {
    "id": "seoul-botanic-park",
    "name": "서울식물원",
    "region": "서울특별시 강서구",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 37.5710656,
    "lng": 126.8346641,
    "description": "서울식물원에서는 열대와 지중해 식물의 생김새와 도시 속 생태계를 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "서로 다른 기후관의 잎 모양을 비교하고 물을 보존하는 방법을 찾아보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://botanicpark.seoul.go.kr/"
  },
  {
    "id": "seoul-grand-park",
    "name": "서울대공원",
    "region": "경기도 과천시",
    "category": "animal",
    "categoryName": "동물·생태",
    "emoji": "🦉",
    "lat": 37.4339353,
    "lng": 127.0113836,
    "description": "서울대공원에서는 동물의 서식환경과 멸종위기종 보전, 식물 생태를 직접 살펴볼 수 있어요. 동물의 행동과 생활 환경을 가까이 관찰하며 책임 있는 관람과 생태 보전을 생각할 수 있어요.",
    "mission": "동물 한 종을 정해 야생과 사육 공간의 공통점과 차이점을 찾아보세요.",
    "season": "봄·가을",
    "weather": "실내·야외 시설 확인",
    "reservation": "먹이주기·체험 시간 확인",
    "officialUrl": "https://grandpark.seoul.go.kr/"
  },
  {
    "id": "seoul-land",
    "name": "서울랜드",
    "region": "경기도 과천시",
    "category": "theme",
    "categoryName": "놀이·테마",
    "emoji": "🎠",
    "lat": 37.4340909,
    "lng": 127.0202634,
    "description": "서울랜드에서는 놀이기구의 회전·낙하 운동과 대형 시설의 안전 운영을 직접 살펴볼 수 있어요. 놀이시설을 즐기는 데서 끝나지 않고 움직임과 공간 설계, 안전장치를 함께 살펴볼 수 있어요.",
    "mission": "놀이기구 하나의 움직임을 화살표로 표시하고 안전장치를 찾아보세요.",
    "season": "봄·가을",
    "weather": "날씨에 따라 일부 제한",
    "reservation": "온라인 예매·운영시간 확인",
    "officialUrl": "https://www.seoulland.co.kr/"
  },
  {
    "id": "aviation-museum",
    "name": "국립항공박물관",
    "region": "서울특별시 강서구",
    "category": "science",
    "categoryName": "과학·진로",
    "emoji": "🔭",
    "lat": 37.5566519,
    "lng": 126.808464,
    "description": "국립항공박물관에서는 비행기의 구조와 조종·관제·정비 직업을 직접 살펴볼 수 있어요. 직접 만지고 비교하며 교과서의 과학 원리를 실제 기술과 현상에 연결할 수 있어요.",
    "mission": "비행기가 뜨고 방향을 바꾸는 데 쓰이는 부분을 세 가지 찾아보세요.",
    "season": "사계절",
    "weather": "실내 이용 가능",
    "reservation": "체험 회차 사전예약 확인",
    "officialUrl": "https://www.aviation.or.kr/"
  },
  {
    "id": "kidzania-seoul",
    "name": "키자니아 서울",
    "region": "서울특별시 송파구",
    "category": "career",
    "categoryName": "직업·생활",
    "emoji": "🧰",
    "lat": 37.5109369,
    "lng": 127.0964062,
    "description": "키자니아 서울에서는 도시를 움직이는 여러 직업의 역할과 협업을 직접 살펴볼 수 있어요. 하나의 결과가 만들어지기까지 필요한 사람과 기술, 과정과 협업을 구체적으로 살펴볼 수 있어요.",
    "mission": "체험한 직업이 다른 직업과 어떤 도움을 주고받는지 연결해 보세요.",
    "season": "사계절",
    "weather": "체험별 실내·야외 확인",
    "reservation": "체험 프로그램 사전예약 확인",
    "officialUrl": "https://www.kidzania.co.kr/"
  },
  {
    "id": "gwacheon-science",
    "name": "국립과천과학관",
    "region": "경기도 과천시",
    "category": "science",
    "categoryName": "과학·진로",
    "emoji": "🔭",
    "lat": 37.4385264,
    "lng": 127.0062002,
    "description": "국립과천과학관에서는 자연사와 첨단기술, 천문우주를 아우르는 체험 전시를 직접 살펴볼 수 있어요. 직접 만지고 비교하며 교과서의 과학 원리를 실제 기술과 현상에 연결할 수 있어요.",
    "mission": "관심 전시 하나에서 관찰한 사실 세 가지와 질문 하나를 남겨 보세요.",
    "season": "사계절",
    "weather": "실내 이용 가능",
    "reservation": "체험 회차 사전예약 확인",
    "officialUrl": "https://www.sciencecenter.go.kr/"
  },
  {
    "id": "korea-job-world",
    "name": "한국잡월드",
    "region": "경기도 성남시",
    "category": "career",
    "categoryName": "직업·생활",
    "emoji": "🧰",
    "lat": 37.3785437,
    "lng": 127.1066161,
    "description": "한국잡월드에서는 현실적인 직업 업무와 진로 탐색, 일터의 협업을 직접 살펴볼 수 있어요. 하나의 결과가 만들어지기까지 필요한 사람과 기술, 과정과 협업을 구체적으로 살펴볼 수 있어요.",
    "mission": "관심 직업에 필요한 능력과 학교에서 준비할 일을 각각 두 가지 적어 보세요.",
    "season": "사계절",
    "weather": "체험별 실내·야외 확인",
    "reservation": "체험 프로그램 사전예약 확인",
    "officialUrl": "https://www.koreajobworld.or.kr/"
  },
  {
    "id": "korean-folk-village",
    "name": "한국민속촌",
    "region": "경기도 용인시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.2594792,
    "lng": 127.1210423,
    "description": "한국민속촌에서는 전통가옥과 농사·공예·공연으로 만나는 조선 생활을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "서로 다른 신분이나 지역의 집 두 채를 골라 구조와 생활을 비교해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.koreanfolk.co.kr/"
  },
  {
    "id": "suwon-hwaseong",
    "name": "수원 화성",
    "region": "경기도 수원시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.2776535,
    "lng": 127.0103363,
    "description": "수원 화성에서는 정조의 도시 계획과 조선 후기 성곽의 과학적 방어 구조를 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "성곽을 걸으며 공격을 막기 위한 시설 세 가지와 역할을 찾아보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.swcf.or.kr/"
  },
  {
    "id": "agriculture-museum",
    "name": "국립농업박물관",
    "region": "경기도 수원시",
    "category": "career",
    "categoryName": "직업·생활",
    "emoji": "🧰",
    "lat": 37.2758335,
    "lng": 126.9823881,
    "description": "국립농업박물관에서는 씨앗에서 식탁까지 이어지는 농업과 식품 생산을 직접 살펴볼 수 있어요. 하나의 결과가 만들어지기까지 필요한 사람과 기술, 과정과 협업을 구체적으로 살펴볼 수 있어요.",
    "mission": "먹거리 하나를 골라 생산·운반·판매 과정을 순서대로 정리해 보세요.",
    "season": "사계절",
    "weather": "체험별 실내·야외 확인",
    "reservation": "체험 프로그램 사전예약 확인",
    "officialUrl": "https://www.namuk.or.kr/"
  },
  {
    "id": "railroad-museum",
    "name": "철도박물관",
    "region": "경기도 의왕시",
    "category": "career",
    "categoryName": "직업·생활",
    "emoji": "🧰",
    "lat": 37.3140179,
    "lng": 126.9508272,
    "description": "철도박물관에서는 철도 차량과 신호, 기관사·관제·정비의 역할을 직접 살펴볼 수 있어요. 하나의 결과가 만들어지기까지 필요한 사람과 기술, 과정과 협업을 구체적으로 살펴볼 수 있어요.",
    "mission": "기차가 안전하게 움직이는 데 필요한 시설과 직업을 세 가지 찾아보세요.",
    "season": "사계절",
    "weather": "체험별 실내·야외 확인",
    "reservation": "체험 프로그램 사전예약 확인",
    "officialUrl": "https://www.railroadmuseum.co.kr/"
  },
  {
    "id": "korea-manhwa-museum",
    "name": "한국만화박물관",
    "region": "경기도 부천시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.5087778,
    "lng": 126.742141,
    "description": "한국만화박물관에서는 만화의 역사와 칸·말풍선·움직임을 표현하는 방법을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "같은 장면을 글 없이 전달하도록 세 칸 만화로 다시 구성해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.komacon.kr/comicsmuseum/"
  },
  {
    "id": "siheung-gaetgol",
    "name": "시흥갯골생태공원",
    "region": "경기도 시흥시",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 37.3921462,
    "lng": 126.7798452,
    "description": "시흥갯골생태공원에서는 내륙 갯골과 옛 염전, 염생식물과 철새 생태를 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "짠물 환경에서 사는 식물이나 동물의 적응 특징을 찾아보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://www.siheung.go.kr/"
  },
  {
    "id": "national-maritime-museum",
    "name": "국립해양박물관",
    "region": "부산광역시 영도구",
    "category": "science",
    "categoryName": "과학·진로",
    "emoji": "🔭",
    "lat": 35.0786526,
    "lng": 129.0802577,
    "description": "국립해양박물관에서는 배와 항해, 해양산업과 바다 생태를 연결한 전시를 직접 살펴볼 수 있어요. 직접 만지고 비교하며 교과서의 과학 원리를 실제 기술과 현상에 연결할 수 있어요.",
    "mission": "옛 항해와 오늘날 항해에서 위치를 알아내는 방법을 비교해 보세요.",
    "season": "사계절",
    "weather": "실내 이용 가능",
    "reservation": "체험 회차 사전예약 확인",
    "officialUrl": "https://www.mmk.or.kr/"
  },
  {
    "id": "busan-science-museum",
    "name": "국립부산과학관",
    "region": "부산광역시 기장군",
    "category": "science",
    "categoryName": "과학·진로",
    "emoji": "🔭",
    "lat": 35.2042335,
    "lng": 129.2128776,
    "description": "국립부산과학관에서는 자동차·항공·선박·에너지 중심의 수송 과학을 직접 살펴볼 수 있어요. 직접 만지고 비교하며 교과서의 과학 원리를 실제 기술과 현상에 연결할 수 있어요.",
    "mission": "수송수단 하나를 골라 움직이게 하는 힘과 방향 조절 장치를 찾아보세요.",
    "season": "사계절",
    "weather": "실내 이용 가능",
    "reservation": "체험 회차 사전예약 확인",
    "officialUrl": "https://www.sciport.or.kr/"
  },
  {
    "id": "gamcheon-village",
    "name": "감천문화마을",
    "region": "부산광역시 사하구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 35.0963371,
    "lng": 129.0087897,
    "description": "감천문화마을에서는 산비탈 마을의 골목과 집, 도시재생과 공공미술을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "경사와 골목 모양이 주민 생활에 주는 장점과 불편을 찾아보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.gamcheon.or.kr/"
  },
  {
    "id": "daegu-national-museum",
    "name": "국립대구박물관",
    "region": "대구광역시 수성구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 35.8458097,
    "lng": 128.6378445,
    "description": "국립대구박물관에서는 대구·경북의 고대문화와 복식·섬유 유산을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "옷이나 장신구 한 점을 골라 재료와 당시 기술을 추리해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://daegu.museum.go.kr/"
  },
  {
    "id": "daegu-education-museum",
    "name": "대구교육박물관",
    "region": "대구광역시 북구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 35.8974195,
    "lng": 128.6123688,
    "description": "대구교육박물관에서는 옛 교실과 교과서, 학교생활의 변화를 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "부모·조부모 세대의 학교생활과 오늘날 학교를 세 가지 기준으로 비교해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.dge.go.kr/dme/"
  },
  {
    "id": "daegu-arboretum",
    "name": "대구수목원",
    "region": "대구광역시 달서구",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 35.7986914,
    "lng": 128.5242901,
    "description": "대구수목원에서는 쓰레기 매립지를 식물원으로 바꾼 도시 생태 복원을 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "이곳이 매립지였다는 흔적과 생태 복원을 보여주는 모습을 찾아보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://www.daegu.go.kr/eco/"
  },
  {
    "id": "world-writing-museum",
    "name": "국립세계문자박물관",
    "region": "인천광역시 연수구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 37.394431,
    "lng": 126.6382789,
    "description": "국립세계문자박물관에서는 세계 문자의 탄생과 기록 방식, 소통의 변화를 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "모양과 쓰는 방향이 다른 문자 세 가지를 골라 공통점을 찾아보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.mow.or.kr/"
  },
  {
    "id": "sorae-wetland",
    "name": "소래습지생태공원",
    "region": "인천광역시 남동구",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 37.4127508,
    "lng": 126.7477937,
    "description": "소래습지생태공원에서는 갯벌과 염전, 소금기 있는 땅의 식물과 철새를 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "갯벌 생물의 구멍과 발자국을 찾아 어떤 행동의 흔적인지 추리해 보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://www.incheon.go.kr/park/"
  },
  {
    "id": "asia-culture-center",
    "name": "국립아시아문화전당",
    "region": "광주광역시 동구",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 35.1472744,
    "lng": 126.9208083,
    "description": "국립아시아문화전당에서는 아시아 문화와 미디어아트, 공연·창작 체험을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "작품 하나를 골라 소리·빛·움직임 중 무엇으로 생각을 전달하는지 찾아보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.acc.go.kr/"
  },
  {
    "id": "mudeungsan",
    "name": "무등산국립공원",
    "region": "광주광역시 동구",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 35.1283952,
    "lng": 126.9960781,
    "description": "무등산국립공원에서는 주상절리와 산지 생태, 도시 가까이의 국립공원을 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "돌기둥의 모양을 관찰하고 용암이 식는 과정과 연결해 설명해 보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://www.knps.or.kr/mudeung"
  },
  {
    "id": "currency-museum",
    "name": "화폐박물관",
    "region": "대전광역시 유성구",
    "category": "career",
    "categoryName": "직업·생활",
    "emoji": "🧰",
    "lat": 36.377535,
    "lng": 127.3705551,
    "description": "화폐박물관에서는 화폐의 역사와 위조 방지 기술, 경제생활을 직접 살펴볼 수 있어요. 하나의 결과가 만들어지기까지 필요한 사람과 기술, 과정과 협업을 구체적으로 살펴볼 수 있어요.",
    "mission": "지폐의 위조 방지 요소 세 가지를 찾아 각각의 원리를 설명해 보세요.",
    "season": "사계절",
    "weather": "체험별 실내·야외 확인",
    "reservation": "체험 프로그램 사전예약 확인",
    "officialUrl": "https://museum.komsco.com/"
  },
  {
    "id": "geological-museum",
    "name": "지질박물관",
    "region": "대전광역시 유성구",
    "category": "science",
    "categoryName": "과학·진로",
    "emoji": "🔭",
    "lat": 36.377308,
    "lng": 127.3631967,
    "description": "지질박물관에서는 광물·암석·화석과 지구의 오랜 변화를 직접 살펴볼 수 있어요. 직접 만지고 비교하며 교과서의 과학 원리를 실제 기술과 현상에 연결할 수 있어요.",
    "mission": "암석 세 개를 골라 색·알갱이·무게를 기준으로 분류해 보세요.",
    "season": "사계절",
    "weather": "실내 이용 가능",
    "reservation": "체험 회차 사전예약 확인",
    "officialUrl": "https://museum.kigam.re.kr/"
  },
  {
    "id": "hanbat-arboretum",
    "name": "한밭수목원",
    "region": "대전광역시 서구",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 36.3649789,
    "lng": 127.3890363,
    "description": "한밭수목원에서는 도심 하천 주변의 식물과 생태 복원을 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "그늘·물·꽃이 곤충과 사람에게 주는 도움을 각각 찾아보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://www.daejeon.go.kr/gar/"
  },
  {
    "id": "daejeon-transport",
    "name": "대전교통문화연수원",
    "region": "대전광역시 유성구",
    "category": "career",
    "categoryName": "직업·생활",
    "emoji": "🧰",
    "lat": 36.3780929,
    "lng": 127.3868634,
    "description": "대전교통문화연수원에서는 보행·자전거·자동차 안전을 실제 상황으로 연습하는 교통 체험을 직접 살펴볼 수 있어요. 하나의 결과가 만들어지기까지 필요한 사람과 기술, 과정과 협업을 구체적으로 살펴볼 수 있어요.",
    "mission": "도로에서 위험을 줄이는 시설 세 가지와 이용 규칙을 찾아보세요.",
    "season": "사계절",
    "weather": "체험별 실내·야외 확인",
    "reservation": "체험 프로그램 사전예약 확인",
    "officialUrl": "https://www.dtcc.or.kr/"
  },
  {
    "id": "whale-museum",
    "name": "장생포고래박물관",
    "region": "울산광역시 남구",
    "category": "animal",
    "categoryName": "동물·생태",
    "emoji": "🦉",
    "lat": 35.5028118,
    "lng": 129.3807531,
    "description": "장생포고래박물관에서는 고래의 몸과 생태, 포경 산업에서 보호 활동으로의 변화를 직접 살펴볼 수 있어요. 동물의 행동과 생활 환경을 가까이 관찰하며 책임 있는 관람과 생태 보전을 생각할 수 있어요.",
    "mission": "고래가 물속 생활에 적응한 몸의 특징을 세 가지 찾아보세요.",
    "season": "봄·가을",
    "weather": "실내·야외 시설 확인",
    "reservation": "먹이주기·체험 시간 확인",
    "officialUrl": "https://www.whalecity.kr/"
  },
  {
    "id": "onggi-village",
    "name": "외고산 옹기마을",
    "region": "울산광역시 울주군",
    "category": "career",
    "categoryName": "직업·생활",
    "emoji": "🧰",
    "lat": 35.4348568,
    "lng": 129.2797553,
    "description": "외고산 옹기마을에서는 흙을 빚고 굽는 옹기 제작과 발효 저장 기술을 직접 살펴볼 수 있어요. 하나의 결과가 만들어지기까지 필요한 사람과 기술, 과정과 협업을 구체적으로 살펴볼 수 있어요.",
    "mission": "옹기의 작은 구멍이 음식 저장에 어떤 도움을 주는지 알아보세요.",
    "season": "사계절",
    "weather": "체험별 실내·야외 확인",
    "reservation": "체험 프로그램 사전예약 확인",
    "officialUrl": "https://onggi.ulju.ulsan.kr/"
  },
  {
    "id": "daewangam-park",
    "name": "대왕암공원",
    "region": "울산광역시 동구",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 35.4923597,
    "lng": 129.4401777,
    "description": "대왕암공원에서는 해안 바위와 소나무숲, 파도와 침식이 만든 지형을 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "바위의 갈라진 틈과 둥근 면을 찾아 파도의 작용과 연결해 보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://www.ulsan.go.kr/s/daewangam"
  },
  {
    "id": "presidential-archives",
    "name": "대통령기록관",
    "region": "세종특별자치시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 36.5015835,
    "lng": 127.2731994,
    "description": "대통령기록관에서는 대통령 기록과 국가 의사결정, 기록 보존의 중요성을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "한 정책 기록을 골라 결정에 필요한 정보와 참여자를 찾아보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.pa.go.kr/"
  },
  {
    "id": "nami-island",
    "name": "남이섬",
    "region": "강원특별자치도 춘천시",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 37.7917285,
    "lng": 127.525144,
    "description": "남이섬에서는 섬의 숲길과 계절 생태, 문화예술 공간을 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "나무가 줄지어 심어진 공간과 자연스럽게 자란 공간의 차이를 찾아보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://www.namisum.com/"
  },
  {
    "id": "choochoo-park",
    "name": "하이원 추추파크",
    "region": "강원특별자치도 삼척시",
    "category": "career",
    "categoryName": "직업·생활",
    "emoji": "🧰",
    "lat": 37.1808291,
    "lng": 129.0387968,
    "description": "하이원 추추파크에서는 산악 철도의 스위치백과 기차·레일바이크 체험을 직접 살펴볼 수 있어요. 하나의 결과가 만들어지기까지 필요한 사람과 기술, 과정과 협업을 구체적으로 살펴볼 수 있어요.",
    "mission": "급한 산길을 기차가 오르는 방법을 선로 모양과 연결해 설명해 보세요.",
    "season": "사계절",
    "weather": "체험별 실내·야외 확인",
    "reservation": "체험 프로그램 사전예약 확인",
    "officialUrl": "https://www.choochoopark.com/"
  },
  {
    "id": "daegwallyeong-sheep",
    "name": "대관령양떼목장",
    "region": "강원특별자치도 평창군",
    "category": "animal",
    "categoryName": "동물·생태",
    "emoji": "🦉",
    "lat": 37.686757,
    "lng": 128.7528354,
    "description": "대관령양떼목장에서는 고산 초지와 양의 먹이·털·생활 방식을 직접 살펴볼 수 있어요. 동물의 행동과 생활 환경을 가까이 관찰하며 책임 있는 관람과 생태 보전을 생각할 수 있어요.",
    "mission": "양의 몸이 바람이 강한 초지 생활에 알맞은 점을 찾아보세요.",
    "season": "봄·가을",
    "weather": "실내·야외 시설 확인",
    "reservation": "먹이주기·체험 시간 확인",
    "officialUrl": "https://www.yangtte.co.kr/"
  },
  {
    "id": "mountain-museum",
    "name": "국립산악박물관",
    "region": "강원특별자치도 속초시",
    "category": "adventure",
    "categoryName": "모험·체육",
    "emoji": "🧗",
    "lat": 38.2027955,
    "lng": 128.5404999,
    "description": "국립산악박물관에서는 등반 역사와 산악 안전, 구조 장비를 직접 살펴볼 수 있어요. 몸을 움직이는 과정에서 힘과 균형, 안전장비와 판단의 중요성을 직접 확인할 수 있어요.",
    "mission": "산에서 길을 잃거나 다쳤을 때 필요한 준비물과 행동을 정리해 보세요.",
    "season": "봄·가을",
    "weather": "기상 악화 시 제한 가능",
    "reservation": "신장·연령·운영 제한 확인",
    "officialUrl": "https://www.fomi.or.kr/"
  },
  {
    "id": "sogeumsan",
    "name": "소금산 그랜드밸리",
    "region": "강원특별자치도 원주시",
    "category": "adventure",
    "categoryName": "모험·체육",
    "emoji": "🧗",
    "lat": 37.3627468,
    "lng": 127.8348827,
    "description": "소금산 그랜드밸리에서는 출렁다리와 잔도에서 살펴보는 산악 지형과 구조 안전을 직접 살펴볼 수 있어요. 몸을 움직이는 과정에서 힘과 균형, 안전장비와 판단의 중요성을 직접 확인할 수 있어요.",
    "mission": "다리를 지탱하는 부분을 찾아 힘이 어디로 전달되는지 표시해 보세요.",
    "season": "봄·가을",
    "weather": "기상 악화 시 제한 가능",
    "reservation": "신장·연령·운영 제한 확인",
    "officialUrl": "https://www.wonju.go.kr/sogeumsan"
  },
  {
    "id": "cheongnamdae",
    "name": "청남대",
    "region": "충청북도 청주시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 36.4622341,
    "lng": 127.490382,
    "description": "청남대에서는 대통령 별장과 현대 정치사, 대청호 주변 환경을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "건물과 산책로가 보안과 휴식이라는 목적에 맞게 배치된 점을 찾아보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://chnam.chungbuk.go.kr/"
  },
  {
    "id": "cheongju-zoo",
    "name": "청주동물원",
    "region": "충청북도 청주시",
    "category": "animal",
    "categoryName": "동물·생태",
    "emoji": "🦉",
    "lat": 36.6520177,
    "lng": 127.5227955,
    "description": "청주동물원에서는 야생동물 구조와 동물복지를 중심으로 운영되는 공영동물원을 직접 살펴볼 수 있어요. 동물의 행동과 생활 환경을 가까이 관찰하며 책임 있는 관람과 생태 보전을 생각할 수 있어요.",
    "mission": "동물이 선택해 숨거나 쉬는 공간을 찾아 동물복지와 연결해 보세요.",
    "season": "봄·가을",
    "weather": "실내·야외 시설 확인",
    "reservation": "먹이주기·체험 시간 확인",
    "officialUrl": "https://www.cheongju.go.kr/zoo/"
  },
  {
    "id": "hwalok-cave",
    "name": "활옥동굴",
    "region": "충청북도 충주시",
    "category": "adventure",
    "categoryName": "모험·체육",
    "emoji": "🧗",
    "lat": 36.9611341,
    "lng": 128.0066559,
    "description": "활옥동굴에서는 광산의 흔적과 동굴 환경, 지하 공간 활용을 직접 살펴볼 수 있어요. 몸을 움직이는 과정에서 힘과 균형, 안전장비와 판단의 중요성을 직접 확인할 수 있어요.",
    "mission": "동굴 안팎의 온도와 습도 차이를 느끼고 그 이유를 추리해 보세요.",
    "season": "봄·가을",
    "weather": "기상 악화 시 제한 가능",
    "reservation": "신장·연령·운영 제한 확인",
    "officialUrl": "https://www.jadecave.co.kr/"
  },
  {
    "id": "independence-hall",
    "name": "독립기념관",
    "region": "충청남도 천안시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 36.783045,
    "lng": 127.224876,
    "description": "독립기념관에서는 독립운동의 흐름과 다양한 참여자의 선택을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "서로 다른 방법으로 독립운동에 참여한 인물 두 명을 비교해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://i815.or.kr/"
  },
  {
    "id": "baekje-culture-land",
    "name": "백제문화단지",
    "region": "충청남도 부여군",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 36.307382,
    "lng": 126.907241,
    "description": "백제문화단지에서는 백제 왕궁과 사찰을 재현한 건축·생활 체험을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "건물의 지붕과 기둥에서 백제 건축의 특징을 세 가지 찾아보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.bhm.or.kr/"
  },
  {
    "id": "chollipo-arboretum",
    "name": "천리포수목원",
    "region": "충청남도 태안군",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 36.7980849,
    "lng": 126.1490319,
    "description": "천리포수목원에서는 바닷바람에 적응한 식물과 다양한 목련·호랑가시나무를 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "잎의 두께와 표면이 바닷바람을 견디는 데 주는 도움을 찾아보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://www.chollipo.org/"
  },
  {
    "id": "cheonan-sangnok",
    "name": "천안상록리조트",
    "region": "충청남도 천안시",
    "category": "theme",
    "categoryName": "놀이·테마",
    "emoji": "🎠",
    "lat": 36.737169,
    "lng": 127.298907,
    "description": "천안상록리조트에서는 가족이 함께 즐기는 놀이·수영·체육 활동을 직접 살펴볼 수 있어요. 놀이시설을 즐기는 데서 끝나지 않고 움직임과 공간 설계, 안전장치를 함께 살펴볼 수 있어요.",
    "mission": "모둠이 함께 이용할 시설을 정하고 안전·시간·비용 기준으로 선택 이유를 설명해 보세요.",
    "season": "봄·가을",
    "weather": "날씨에 따라 일부 제한",
    "reservation": "온라인 예매·운영시간 확인",
    "officialUrl": "https://www.sangnokresort.co.kr/"
  },
  {
    "id": "gongju-museum",
    "name": "국립공주박물관",
    "region": "충청남도 공주시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 36.4655287,
    "lng": 127.1122874,
    "description": "국립공주박물관에서는 무령왕릉 출토품으로 살펴보는 백제의 기술과 국제교류를 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "출토품 하나에서 백제가 다른 나라와 교류한 흔적을 찾아보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://gongju.museum.go.kr/"
  },
  {
    "id": "taekwondowon",
    "name": "태권도원",
    "region": "전북특별자치도 무주군",
    "category": "adventure",
    "categoryName": "모험·체육",
    "emoji": "🧗",
    "lat": 36.0095801,
    "lng": 127.7754294,
    "description": "태권도원에서는 태권도 수련과 시범, 전통무예의 예절과 자기조절을 직접 살펴볼 수 있어요. 몸을 움직이는 과정에서 힘과 균형, 안전장비와 판단의 중요성을 직접 확인할 수 있어요.",
    "mission": "동작의 힘보다 균형과 예절이 중요한 순간을 찾아 설명해 보세요.",
    "season": "봄·가을",
    "weather": "기상 악화 시 제한 가능",
    "reservation": "신장·연령·운영 제한 확인",
    "officialUrl": "https://www.tpf.or.kr/t1/"
  },
  {
    "id": "saemangeum-museum",
    "name": "국립새만금간척박물관",
    "region": "전북특별자치도 부안군",
    "category": "science",
    "categoryName": "과학·진로",
    "emoji": "🔭",
    "lat": 35.6963142,
    "lng": 126.5567418,
    "description": "국립새만금간척박물관에서는 간척의 원리와 방조제 건설, 환경 변화와 선택을 직접 살펴볼 수 있어요. 직접 만지고 비교하며 교과서의 과학 원리를 실제 기술과 현상에 연결할 수 있어요.",
    "mission": "간척으로 얻는 점과 생태계가 잃는 점을 자료로 하나씩 찾아보세요.",
    "season": "사계절",
    "weather": "실내 이용 가능",
    "reservation": "체험 회차 사전예약 확인",
    "officialUrl": "https://www.nsrm.or.kr/"
  },
  {
    "id": "gunsan-modern-museum",
    "name": "군산근대역사박물관",
    "region": "전북특별자치도 군산시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 35.990814,
    "lng": 126.712203,
    "description": "군산근대역사박물관에서는 항구도시 군산의 근대 산업과 일제강점기 생활을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "항구를 통해 들어오고 나간 물건이 도시를 어떻게 바꿨는지 찾아보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://museum.gunsan.go.kr/"
  },
  {
    "id": "gochang-dolmen-museum",
    "name": "고창고인돌박물관",
    "region": "전북특별자치도 고창군",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 35.4417562,
    "lng": 126.6523347,
    "description": "고창고인돌박물관에서는 고인돌의 구조와 청동기 공동체, 세계유산의 보존을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "고인돌의 크기와 위치를 보고 만든 사람들의 협력 규모를 추리해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.gochang.go.kr/gcdolmen/"
  },
  {
    "id": "suncheon-wetland",
    "name": "순천만습지",
    "region": "전라남도 순천시",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 34.8866784,
    "lng": 127.5074978,
    "description": "순천만습지에서는 갈대밭과 갯벌, 흑두루미가 살아가는 연안습지를 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "갈대·갯벌·물길이 철새에게 주는 도움을 각각 찾아보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://scbay.suncheon.go.kr/"
  },
  {
    "id": "suncheon-garden",
    "name": "순천만국가정원",
    "region": "전라남도 순천시",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 34.9266193,
    "lng": 127.510122,
    "description": "순천만국가정원에서는 세계 여러 지역의 정원과 도시 생태·조경 설계를 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "서로 다른 나라 정원 두 곳의 식물·길·물 사용 방식을 비교해 보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://scgardens.or.kr/"
  },
  {
    "id": "aquaplanet-yeosu",
    "name": "아쿠아플라넷 여수",
    "region": "전라남도 여수시",
    "category": "animal",
    "categoryName": "동물·생태",
    "emoji": "🦉",
    "lat": 34.7462815,
    "lng": 127.7486237,
    "description": "아쿠아플라넷 여수에서는 남해의 해양생물과 대형 수조의 생태 관계를 직접 살펴볼 수 있어요. 동물의 행동과 생활 환경을 가까이 관찰하며 책임 있는 관람과 생태 보전을 생각할 수 있어요.",
    "mission": "수조 속 생물을 먹이 관계로 연결해 간단한 먹이그물을 만들어 보세요.",
    "season": "봄·가을",
    "weather": "실내·야외 시설 확인",
    "reservation": "먹이주기·체험 시간 확인",
    "officialUrl": "https://www.aquaplanet.co.kr/yeosu/"
  },
  {
    "id": "naro-space-center",
    "name": "나로우주센터 우주과학관",
    "region": "전라남도 고흥군",
    "category": "science",
    "categoryName": "과학·진로",
    "emoji": "🔭",
    "lat": 34.4536346,
    "lng": 127.5176468,
    "description": "나로우주센터 우주과학관에서는 로켓 발사와 인공위성, 우주센터의 여러 직업을 직접 살펴볼 수 있어요. 직접 만지고 비교하며 교과서의 과학 원리를 실제 기술과 현상에 연결할 수 있어요.",
    "mission": "로켓이 발사되기 전 확인해야 할 조건을 세 가지 찾아보세요.",
    "season": "사계절",
    "weather": "실내 이용 가능",
    "reservation": "체험 회차 사전예약 확인",
    "officialUrl": "https://www.kari.re.kr/narospace/"
  },
  {
    "id": "juknokwon",
    "name": "담양 죽녹원",
    "region": "전라남도 담양군",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 35.3180322,
    "lng": 126.9755357,
    "description": "담양 죽녹원에서는 대나무숲의 빠른 성장과 전통생활 속 대나무 활용을 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "대나무의 줄기와 잎이 빽빽한 숲에서 살아가는 데 유리한 점을 찾아보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://www.juknokwon.go.kr/"
  },
  {
    "id": "mokpo-cable-car",
    "name": "목포해상케이블카",
    "region": "전라남도 목포시",
    "category": "adventure",
    "categoryName": "모험·체육",
    "emoji": "🧗",
    "lat": 34.7855155,
    "lng": 126.3723484,
    "description": "목포해상케이블카에서는 바다와 산을 잇는 케이블 이동과 목포 항구 지형을 직접 살펴볼 수 있어요. 몸을 움직이는 과정에서 힘과 균형, 안전장비와 판단의 중요성을 직접 확인할 수 있어요.",
    "mission": "높은 곳에서 항구·섬·도시가 연결되는 모습을 간단한 지도로 그려 보세요.",
    "season": "봄·가을",
    "weather": "기상 악화 시 제한 가능",
    "reservation": "신장·연령·운영 제한 확인",
    "officialUrl": "https://www.mmcablecar.com/"
  },
  {
    "id": "yeosu-cable-car",
    "name": "여수해상케이블카",
    "region": "전라남도 여수시",
    "category": "adventure",
    "categoryName": "모험·체육",
    "emoji": "🧗",
    "lat": 34.7355029,
    "lng": 127.7472571,
    "description": "여수해상케이블카에서는 바다 위 케이블카의 구조와 여수의 섬·항만 지형을 직접 살펴볼 수 있어요. 몸을 움직이는 과정에서 힘과 균형, 안전장비와 판단의 중요성을 직접 확인할 수 있어요.",
    "mission": "탑승장과 지지탑이 케이블을 안전하게 유지하는 방법을 찾아보세요.",
    "season": "봄·가을",
    "weather": "기상 악화 시 제한 가능",
    "reservation": "신장·연령·운영 제한 확인",
    "officialUrl": "https://yeosucablecar.com/"
  },
  {
    "id": "seokguram",
    "name": "석굴암",
    "region": "경상북도 경주시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 35.7948033,
    "lng": 129.3491954,
    "description": "석굴암에서는 통일신라의 인공 석굴과 불상 조각, 돔 구조를 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "돌을 쌓아 둥근 천장을 만든 방법을 관찰하고 힘의 방향을 생각해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.bulguksa.or.kr/"
  },
  {
    "id": "gyeongju-museum",
    "name": "국립경주박물관",
    "region": "경상북도 경주시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 35.8289946,
    "lng": 129.2279662,
    "description": "국립경주박물관에서는 신라의 금관·불교미술·왕경 생활을 보여주는 유물을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "금관이나 장신구에서 반복되는 무늬와 제작 기술을 찾아보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://gyeongju.museum.go.kr/"
  },
  {
    "id": "baekdudaegan-arboretum",
    "name": "국립백두대간수목원",
    "region": "경상북도 봉화군",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 37.0050546,
    "lng": 128.8107959,
    "description": "국립백두대간수목원에서는 백두대간 산림생태와 종자 보전, 호랑이숲을 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "산지 기후에 적응한 식물의 특징과 종자를 보관하는 이유를 찾아보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://www.bdna.or.kr/"
  },
  {
    "id": "lighthouse-museum",
    "name": "국립등대박물관",
    "region": "경상북도 포항시",
    "category": "science",
    "categoryName": "과학·진로",
    "emoji": "🔭",
    "lat": 36.0778126,
    "lng": 129.5685148,
    "description": "국립등대박물관에서는 등대의 빛과 렌즈, 선박의 안전한 항로를 직접 살펴볼 수 있어요. 직접 만지고 비교하며 교과서의 과학 원리를 실제 기술과 현상에 연결할 수 있어요.",
    "mission": "등대 빛이 멀리 보이도록 만드는 장치와 신호 방법을 찾아보세요.",
    "season": "사계절",
    "weather": "실내 이용 가능",
    "reservation": "체험 회차 사전예약 확인",
    "officialUrl": "https://www.lighthouse-museum.or.kr/"
  },
  {
    "id": "upo-wetland",
    "name": "우포늪",
    "region": "경상남도 창녕군",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 35.5530211,
    "lng": 128.4148227,
    "description": "우포늪에서는 오래된 자연습지의 물길과 새·물고기·수생식물을 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "물의 깊이가 다른 곳에서 사는 생물의 차이를 관찰해 보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://www.cng.go.kr/upo/"
  },
  {
    "id": "jinju-museum",
    "name": "국립진주박물관",
    "region": "경상남도 진주시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 35.1890527,
    "lng": 128.0767991,
    "description": "국립진주박물관에서는 임진왜란과 진주성, 무기와 기록으로 보는 전쟁을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "같은 전투를 보여주는 무기와 기록을 연결해 당시 상황을 설명해 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://jinju.museum.go.kr/"
  },
  {
    "id": "miryang-weather-science",
    "name": "국립밀양기상과학관",
    "region": "경상남도 밀양시",
    "category": "science",
    "categoryName": "과학·진로",
    "emoji": "🔭",
    "lat": 35.5021349,
    "lng": 128.7605517,
    "description": "국립밀양기상과학관에서는 구름·비·바람과 기상 관측, 재해 대비를 직접 살펴볼 수 있어요. 직접 만지고 비교하며 교과서의 과학 원리를 실제 기술과 현상에 연결할 수 있어요.",
    "mission": "날씨를 측정하는 장비 하나를 골라 무엇을 어떻게 재는지 설명해 보세요.",
    "season": "사계절",
    "weather": "실내 이용 가능",
    "reservation": "체험 회차 사전예약 확인",
    "officialUrl": "https://science.kma.go.kr/science/"
  },
  {
    "id": "geoje-pow-camp",
    "name": "거제포로수용소유적공원",
    "region": "경상남도 거제시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 34.8760819,
    "lng": 128.6246009,
    "description": "거제포로수용소유적공원에서는 한국전쟁 포로의 생활과 갈등, 전쟁 인권을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "포로의 생활을 보여주는 자료에서 전쟁이 개인에게 준 영향을 찾아보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.gmdc.co.kr/_pow/"
  },
  {
    "id": "tongyeong-luge",
    "name": "통영 스카이라인루지",
    "region": "경상남도 통영시",
    "category": "adventure",
    "categoryName": "모험·체육",
    "emoji": "🧗",
    "lat": 34.8231481,
    "lng": 128.425417,
    "description": "통영 스카이라인루지에서는 중력으로 내려가는 카트의 조향·제동과 안전을 직접 살펴볼 수 있어요. 몸을 움직이는 과정에서 힘과 균형, 안전장비와 판단의 중요성을 직접 확인할 수 있어요.",
    "mission": "경사와 속도의 관계를 느끼고 브레이크가 움직임을 바꾸는 과정을 설명해 보세요.",
    "season": "봄·가을",
    "weather": "기상 악화 시 제한 가능",
    "reservation": "신장·연령·운영 제한 확인",
    "officialUrl": "https://skylineluge.kr/tongyeong/"
  },
  {
    "id": "goseong-dinosaur",
    "name": "고성공룡박물관",
    "region": "경상남도 고성군",
    "category": "science",
    "categoryName": "과학·진로",
    "emoji": "🔭",
    "lat": 34.9080412,
    "lng": 128.1485631,
    "description": "고성공룡박물관에서는 공룡 발자국 화석과 백악기 한반도의 환경을 직접 살펴볼 수 있어요. 직접 만지고 비교하며 교과서의 과학 원리를 실제 기술과 현상에 연결할 수 있어요.",
    "mission": "발자국 크기와 간격으로 공룡의 크기와 움직임을 추리해 보세요.",
    "season": "사계절",
    "weather": "실내 이용 가능",
    "reservation": "체험 회차 사전예약 확인",
    "officialUrl": "https://museum.goseong.go.kr/"
  },
  {
    "id": "seongsan-ilchulbong",
    "name": "성산일출봉",
    "region": "제주특별자치도 서귀포시",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 33.4588891,
    "lng": 126.9408178,
    "description": "성산일출봉에서는 바닷속 화산 분출로 생긴 응회구와 해안 생태를 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "층층이 쌓인 화산재 지층을 찾아 분출 당시 모습을 상상해 보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://www.jeju.go.kr/jejuwnh/"
  },
  {
    "id": "jeju43-peace",
    "name": "제주4·3평화공원",
    "region": "제주특별자치도 제주시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 33.4514768,
    "lng": 126.6172799,
    "description": "제주4·3평화공원에서는 제주4·3의 희생과 기억, 평화·인권 교육을 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "한 사람의 증언이나 기록을 골라 기억을 보존해야 하는 이유를 적어 보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://jeju43peace.or.kr/"
  },
  {
    "id": "jeju-world-heritage",
    "name": "제주세계자연유산센터",
    "region": "제주특별자치도 제주시",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 33.4569395,
    "lng": 126.7146401,
    "description": "제주세계자연유산센터에서는 한라산·용암동굴·성산일출봉의 형성 과정을 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "제주의 세 자연유산이 모두 화산과 연결되는 과정을 정리해 보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://www.jeju.go.kr/jejuwnh/"
  },
  {
    "id": "snoopy-garden",
    "name": "스누피가든",
    "region": "제주특별자치도 제주시",
    "category": "nature",
    "categoryName": "자연·생태",
    "emoji": "🌿",
    "lat": 33.4447426,
    "lng": 126.7797014,
    "description": "스누피가든에서는 제주 숲과 정원, 캐릭터 이야기가 결합된 야외 공간을 직접 살펴볼 수 있어요. 지형과 식물, 동물의 관계를 현장에서 관찰하며 자연환경이 서로 연결되는 방식을 배울 수 있어요.",
    "mission": "정원의 식물과 조형물이 하나의 이야기를 만드는 장면을 찾아보세요.",
    "season": "봄·가을",
    "weather": "날씨·탐방로 상태 확인",
    "reservation": "개방시간·탐방 안내 확인",
    "officialUrl": "https://snoopygarden.com/"
  },
  {
    "id": "hueree",
    "name": "휴애리 자연생활공원",
    "region": "제주특별자치도 서귀포시",
    "category": "career",
    "categoryName": "직업·생활",
    "emoji": "🧰",
    "lat": 33.308337,
    "lng": 126.632868,
    "description": "휴애리 자연생활공원에서는 감귤 재배와 계절 꽃, 동물 돌봄을 함께 하는 농촌 체험을 직접 살펴볼 수 있어요. 하나의 결과가 만들어지기까지 필요한 사람과 기술, 과정과 협업을 구체적으로 살펴볼 수 있어요.",
    "mission": "감귤이 열매가 되어 수확되기까지 농부가 하는 일을 순서대로 적어 보세요.",
    "season": "사계절",
    "weather": "체험별 실내·야외 확인",
    "reservation": "체험 프로그램 사전예약 확인",
    "officialUrl": "https://hueree.com/"
  },
  {
    "id": "ecoland-jeju",
    "name": "에코랜드 테마파크",
    "region": "제주특별자치도 제주시",
    "category": "theme",
    "categoryName": "놀이·테마",
    "emoji": "🎠",
    "lat": 33.4608356,
    "lng": 126.6720778,
    "description": "에코랜드 테마파크에서는 곶자왈 숲을 기차로 이동하며 만나는 제주 생태를 직접 살펴볼 수 있어요. 놀이시설을 즐기는 데서 끝나지 않고 움직임과 공간 설계, 안전장치를 함께 살펴볼 수 있어요.",
    "mission": "곶자왈의 돌·나무·습기가 생물에게 만드는 환경을 관찰해 보세요.",
    "season": "봄·가을",
    "weather": "날씨에 따라 일부 제한",
    "reservation": "온라인 예매·운영시간 확인",
    "officialUrl": "https://www.ecolandjeju.co.kr/"
  },
  {
    "id": "jeju-folk-village",
    "name": "제주민속촌",
    "region": "제주특별자치도 서귀포시",
    "category": "culture",
    "categoryName": "역사·문화",
    "emoji": "🏛️",
    "lat": 33.3227091,
    "lng": 126.8416229,
    "description": "제주민속촌에서는 바람과 돌이 많은 제주에 적응한 집과 생활도구를 직접 살펴볼 수 있어요. 현장의 건물과 기록, 유물을 연결하면 사람들의 선택과 생활이 어떻게 달라졌는지 이해할 수 있어요.",
    "mission": "돌담·지붕·마당이 제주 바람과 비에 대응하는 방법을 찾아보세요.",
    "season": "사계절",
    "weather": "실내·야외 동선 확인",
    "reservation": "해설·휴관일 확인",
    "officialUrl": "https://www.jejufolk.com/"
  }
]);
