export type ArithmeticWorksheet = {
  name: string;
  route: string | null;
  grade: string;
  title: string;
  badge?: "암산" | "암기";
};

const readyRoutes: Record<string, string> = {
  "1수세기①": "/arithmetic/counting-1",
  "1덧셈뺄셈①": "/arithmetic/add-subtract-1",
  "1덧셈뺄셈②": "/arithmetic/add-subtract-2",
  "1주고받기": "/arithmetic/give-and-take-1",
  "1보수": "/arithmetic/complements-1",
  "1덧셈뺄셈③": "/arithmetic/add-subtract-3",
  "1덧셈뺄셈④": "/arithmetic/add-subtract-4",
  "1수읽기": "/arithmetic/number-reading-1",
  "1뛰어세기": "/arithmetic/skip-counting-1",
  "2덧셈뺄셈①": "/arithmetic/grade-2-add-subtract-1",
  "2덧셈뺄셈②": "/arithmetic/grade-2-add-subtract-2",
  "2덧셈뺄셈③": "/arithmetic/grade-2-add-subtract-3",
  "2묶어세기": "/arithmetic/group-counting-1",
  "2구구단①": "/arithmetic/multiplication-1",
  "2구구단②": "/arithmetic/multiplication-2",
  "2구구단③": "/arithmetic/multiplication-3",
  "2구구단④": "/arithmetic/multiplication-4",
  "2구구단⑤": "/arithmetic/multiplication-5",
  "2시계": "/arithmetic/clock-1",
  "3덧셈뺄셈": "/arithmetic/grade-3-add-subtract",
  "3덧셈뺄셈빈칸": "/arithmetic/grade-3-add-subtract-blanks",
  "3보수뺄셈100": "/arithmetic/grade-3-complement-subtraction-100",
  "3보수뺄셈1000": "/arithmetic/grade-3-complement-subtraction-1000",
  "3덧셈뺄셈②": "/arithmetic/grade-3-add-subtract-2",
  "3나눗셈①": "/arithmetic/grade-3-division-1",
  "3곱셈①": "/arithmetic/grade-3-multiplication-1",
  "3곱셈②": "/arithmetic/grade-3-multiplication-2",
  "3길이": "/arithmetic/grade-3-length",
  "3시간①": "/arithmetic/grade-3-time-1",
  "3시간②": "/arithmetic/grade-3-time-2",
  "3곱셈③": "/arithmetic/grade-3-multiplication-3",
  "19단": "/arithmetic/nineteen-times-table",
  "제곱수": "/arithmetic/square-numbers",
  "3나눗셈②": "/arithmetic/grade-3-division-2",
  "3나눗셈③": "/arithmetic/grade-3-division-3",
  "3분수①": "/arithmetic/grade-3-fraction-1",
  "3분수②": "/fraction",
  "3무게,들이": "/arithmetic/grade-3-measurement",
  "3분수③": "/arithmetic/grade-3-fraction-3",
  "4숫자읽기": "/arithmetic/grade-4-number-reading",
  "4각도어림": "/arithmetic/grade-4-angle-estimation",
  "4곱셈": "/arithmetic/grade-4-multiplication",
  "4큰수곱셈": "/arithmetic/grade-4-large-number-multiplication",
  "4나눗셈": "/arithmetic/grade-4-division",
  "4분수": "/arithmetic/grade-4-fraction",
  "4소수": "/arithmetic/grade-4-decimals",
  "단위변환": "/arithmetic/unit-conversion",
  "5혼합계산": "/arithmetic/grade-5-mixed-calculation",
  "자연수분해": "/arithmetic/grade-5-natural-number-decomposition",
  "프라임넘버": "/arithmetic/grade-5-prime-numbers",
  "5약수,배수": "/arithmetic/grade-5-divisors-multiples",
  "5분수①": "/arithmetic/grade-5-fraction-1",
  "5분수②": "/arithmetic/grade-5-fraction-2",
  "5분수③": "/arithmetic/grade-5-fraction-3",
  "5소수": "/arithmetic/grade-5-decimals",
  "6분수": "/arithmetic/grade-6-fraction",
  "6소수①": "/arithmetic/grade-6-decimals-1",
  "6소수②": "/arithmetic/grade-6-decimals-2",
  "6소수③": "/arithmetic/grade-6-decimals-3",
  "6혼합계산": "/arithmetic/grade-6-mixed-calculation",
  "6비례식": "/arithmetic/grade-6-proportion",
  "6원": "/arithmetic/grade-6-circle",
  "6원기둥": "/arithmetic/grade-6-cylinder",
  "6쌓기나무": "/arithmetic/grade-6-stacked-cubes",
};

const worksheetNames = [
  "1수세기①", "1덧셈뺄셈①", "1덧셈뺄셈②", "1주고받기", "1보수", "1덧셈뺄셈③", "1덧셈뺄셈④", "1수읽기", "1뛰어세기",
  "2덧셈뺄셈①", "2덧셈뺄셈②", "2덧셈뺄셈③", "2묶어세기", "2구구단①", "2구구단②", "2구구단③", "2구구단④", "2구구단⑤", "2시계",
  "3덧셈뺄셈", "3덧셈뺄셈빈칸", "3보수뺄셈100", "3보수뺄셈1000", "3덧셈뺄셈②", "3나눗셈①", "3곱셈①", "3곱셈②", "3길이", "3시간①", "3시간②", "3곱셈③", "19단", "제곱수", "3나눗셈②", "3나눗셈③", "3분수①", "3분수②", "3무게,들이", "3분수③",
  "4숫자읽기", "4각도어림", "4곱셈", "4큰수곱셈", "4나눗셈", "4분수", "4소수", "단위변환",
  "5혼합계산", "자연수분해", "프라임넘버", "5약수,배수", "5분수①", "5분수②", "5분수③", "5소수",
  "6분수", "6소수①", "6소수②", "6소수③", "6혼합계산", "6비례식", "6원", "6원기둥", "6쌓기나무",
] as const;

const explicitGrades: Record<string, string> = {
  "19단": "3",
  "제곱수": "3",
  "단위변환": "4",
  "자연수분해": "5",
  "프라임넘버": "5",
};

const elementaryTitles: Record<string, string> = {
  "1수세기①": "1부터 9까지 수 세기",
  "1덧셈뺄셈①": "한 자리 수 덧셈·뺄셈",
  "1덧셈뺄셈②": "두 자리 수 덧셈·뺄셈",
  "1주고받기": "주고받은 뒤의 수 구하기",
  "1보수": "10 모으기·가르기",
  "1덧셈뺄셈③": "10을 넘는 덧셈·뺄셈",
  "1덧셈뺄셈④": "덧셈·뺄셈 빈칸 채우기",
  "1수읽기": "두 자리 수 읽기",
  "1뛰어세기": "뛰어 세기",
  "2덧셈뺄셈①": "덧셈·뺄셈 ①",
  "2덧셈뺄셈②": "덧셈·뺄셈 ②",
  "2덧셈뺄셈③": "덧셈·뺄셈 ③",
  "2묶어세기": "묶어 세기",
  "2구구단①": "구구단(2·5단)",
  "2구구단②": "구구단(3·4단)",
  "2구구단③": "구구단(6·7단)",
  "2구구단④": "구구단(8·9단)",
  "2구구단⑤": "구구단(종합)",
  "2시계": "시각 읽기와 쓰기",
  "3덧셈뺄셈": "세 자리 수의 덧셈·뺄셈",
  "3덧셈뺄셈빈칸": "덧셈·뺄셈 빈칸",
  "3보수뺄셈100": "보수 뺄셈(100)",
  "3보수뺄셈1000": "보수 뺄셈(1000)",
  "3덧셈뺄셈②": "덧셈·뺄셈 ②",
  "3나눗셈①": "나눗셈 ①",
  "3곱셈①": "곱셈 ①",
  "3곱셈②": "곱셈 ②",
  "3길이": "길이의 계산",
  "3시간①": "시간의 계산 ①",
  "3시간②": "시간의 계산 ②",
  "3곱셈③": "곱셈 ③",
  "19단": "19단 곱셈",
  "제곱수": "제곱수",
  "3나눗셈②": "나눗셈 ②",
  "3나눗셈③": "나눗셈 ③",
  "3분수①": "분수 ①",
  "3분수②": "분수 ②",
  "3무게,들이": "무게와 들이",
  "3분수③": "분수 ③",
  "4숫자읽기": "큰 수 읽기·쓰기",
  "4각도어림": "각도의 어림",
  "4곱셈": "여러 자리 수의 곱셈",
  "4큰수곱셈": "큰 수 단위의 곱셈",
  "4나눗셈": "세 자리 수 ÷ 두 자리 수",
  "4분수": "분모가 같은 대분수의 덧셈·뺄셈",
  "4소수": "소수의 덧셈·뺄셈",
  "단위변환": "길이의 단위 변환",
  "5혼합계산": "자연수의 혼합 계산",
  "자연수분해": "자연수를 소수의 곱으로 나타내기",
  "프라임넘버": "소수(素數) 찾기",
  "5약수,배수": "최대공약수·최소공배수",
  "5분수①": "분수의 덧셈·뺄셈·곱셈",
  "5분수②": "대분수의 덧셈·뺄셈·곱셈",
  "5분수③": "분수의 크기 비교",
  "5소수": "소수의 곱셈",
  "6분수": "분수의 사칙 계산",
  "6소수①": "자연수 ÷ 자연수의 몫을 소수로 나타내기",
  "6소수②": "소수의 곱셈·나눗셈과 반올림",
  "6소수③": "소수의 나눗셈과 몫·나머지",
  "6혼합계산": "분수·소수 혼합 계산",
  "6비례식": "비와 비례식",
  "6원": "원의 둘레와 넓이",
  "6원기둥": "원기둥의 겉넓이와 부피",
  "6쌓기나무": "쌓기나무의 개수와 세 방향 모양",
};

// 자동 분류를 그만두고, 사용자가 지정하는 학습지만 하나씩 추가한다.
const elementaryHorizontalMentalMathWorksheets = new Set<string>([
  "2덧셈뺄셈③",
  "3덧셈뺄셈②",
  "3보수뺄셈100",
  "3보수뺄셈1000",
  "3곱셈②",
  "19단",
  "4큰수곱셈",
  "5약수,배수",
  "5분수③",
  "6소수①",
]);
const elementaryMemorizationWorksheets = new Set<string>(["제곱수"]);

export const arithmeticWorksheetCatalog: ArithmeticWorksheet[] = worksheetNames.map((name) => {
  const gradeMatch = name.match(/^([1-6])(?!\d)(.+)$/);
  const grade = explicitGrades[name] ?? gradeMatch?.[1] ?? "";
  return {
    name,
    route: readyRoutes[name] ?? null,
    grade: `초${grade}`,
    title: elementaryTitles[name] ?? (explicitGrades[name] ? name : gradeMatch ? gradeMatch[2] : name),
    badge: elementaryMemorizationWorksheets.has(name) ? "암기" : elementaryHorizontalMentalMathWorksheets.has(name) ? "암산" : undefined,
  };
});

const mergedMiddleSchoolRoutes = new Set([
  "/arithmetic/middle-school/core-calculations?kind=linear-equation-application",
  "/arithmetic/middle-school/core-calculations?kind=square-roots-real",
  "/arithmetic/middle-school/quadratic-equations?kind=roots-and-squares",
  "/arithmetic/middle-school/trigonometry?kind=special-angles",
  "/arithmetic/middle-school/trigonometry?kind=comprehensive",
  "/arithmetic/middle-school/circle-properties?kind=angle-applications",
  "/arithmetic/middle-school/circle-properties?kind=comprehensive",
  "/arithmetic/middle-school/statistics?kind=mean-applications",
]);

const combinedMiddleSchoolTitles: Record<string, string> = {
  "/arithmetic/middle-school/core-calculations?kind=linear-equation": "일차방정식과 활용 계산",
  "/arithmetic/middle-school/core-calculations?kind=radical-calculation": "제곱근과 근호 계산",
  "/arithmetic/middle-school/trigonometry?kind=ratios": "삼각비의 값과 특수각",
  "/arithmetic/middle-school/circle-properties?kind=inscribed-angles": "원주각과 각의 응용",
  "/arithmetic/middle-school/statistics?kind=representative-values": "대푯값·도수·상대도수",
};

export const middleSchoolWorksheetCatalog: ArithmeticWorksheet[] = [
  { grade: "중1", name: "소인수분해", title: "소인수분해", route: "/arithmetic/middle-school/core-calculations?kind=prime-factorization" },
  { grade: "중1", name: "최대공약수와 최소공배수", title: "최대공약수와 최소공배수", route: "/arithmetic/middle-school/core-calculations?kind=gcd-lcm" },
  { grade: "중1", name: "정수와 유리수의 기초·혼합계산", title: "정수와 유리수의 기초·혼합계산", route: "/arithmetic/middle-school/rational-mixed" },
  { grade: "중1", name: "일차식의 계산", title: "일차식의 계산", route: "/arithmetic/middle-school/core-calculations?kind=linear-expression" },
  { grade: "중1", name: "일차방정식", title: "일차방정식", route: "/arithmetic/middle-school/core-calculations?kind=linear-equation" },
  { grade: "중1", name: "일차방정식 활용 계산", title: "일차방정식 활용 계산", route: "/arithmetic/middle-school/core-calculations?kind=linear-equation-application" },
  { grade: "중1", name: "좌표·정비례·반비례 계산", title: "좌표·정비례·반비례 계산", route: "/arithmetic/middle-school/curriculum-calculations?kind=coordinate-proportion" },
  { grade: "중1", name: "기본도형·작도·합동", title: "기본도형·작도·합동", route: "/arithmetic/middle-school/curriculum-calculations?kind=construction-congruence" },
  { grade: "중1", name: "기본각·다각형·부채꼴 계산", title: "기본각·다각형·부채꼴 계산", route: "/arithmetic/middle-school/curriculum-calculations?kind=plane-geometry" },
  { grade: "중1", name: "입체도형의 겉넓이와 부피", title: "입체도형의 겉넓이와 부피", route: "/arithmetic/middle-school/curriculum-calculations?kind=solid-geometry" },
  { grade: "중1", name: "대푯값·도수·상대도수", title: "대푯값·도수·상대도수", route: "/arithmetic/middle-school/statistics?kind=representative-values" },

  { grade: "중2", name: "유리수와 순환소수", title: "유리수와 순환소수", route: "/arithmetic/middle-school/core-calculations?kind=repeating-decimal" },
  { grade: "중2", name: "지수법칙", title: "지수법칙", route: "/arithmetic/middle-school/core-calculations?kind=exponent-laws" },
  { grade: "중2", name: "문자식 기본연산 종합", title: "문자식 기본연산 종합", route: "/arithmetic/middle-school/core-calculations?kind=polynomial-add-subtract" },
  { grade: "중2", name: "일차부등식", title: "일차부등식", route: "/arithmetic/middle-school/core-calculations?kind=linear-inequality" },
  { grade: "중2", name: "일차부등식 활용", title: "일차부등식 활용", route: "/arithmetic/middle-school/core-calculations?kind=linear-inequality-application" },
  { grade: "중2", name: "연립방정식 대입법", title: "연립방정식 대입법", route: "/arithmetic/middle-school/core-calculations?kind=simultaneous-substitution" },
  { grade: "중2", name: "연립방정식 가감법", title: "연립방정식 가감법", route: "/arithmetic/middle-school/core-calculations?kind=simultaneous-elimination" },
  { grade: "중2", name: "연립방정식 활용", title: "연립방정식 활용", route: "/arithmetic/middle-school/core-calculations?kind=simultaneous-application" },
  { grade: "중2", name: "연립방정식의 해의 개수", title: "연립방정식의 해의 개수", route: "/arithmetic/middle-school/core-calculations?kind=simultaneous-special" },
  { grade: "중2", name: "일차함수", title: "일차함수", route: "/arithmetic/middle-school/curriculum-calculations?kind=linear-function-basics" },
  { grade: "중2", name: "삼각형과 사각형의 계산", title: "삼각형과 사각형의 계산", route: "/arithmetic/middle-school/curriculum-calculations?kind=triangle-quadrilateral" },
  { grade: "중2", name: "피타고라스 정리 계산", title: "피타고라스 정리 계산", route: "/arithmetic/middle-school/curriculum-calculations?kind=pythagorean" },
  { grade: "중2", name: "경우의 수와 확률 계산", title: "경우의 수와 확률 계산", route: "/arithmetic/middle-school/curriculum-calculations?kind=counting-probability" },

  { grade: "중3", name: "제곱근과 실수", title: "제곱근과 실수", route: "/arithmetic/middle-school/core-calculations?kind=square-roots-real" },
  { grade: "중3", name: "근호를 포함한 식의 계산", title: "근호를 포함한 식의 계산", route: "/arithmetic/middle-school/core-calculations?kind=radical-calculation" },
  { grade: "중3", name: "다항식의 곱셈과 곱셈공식", title: "다항식의 곱셈과 곱셈공식", route: "/arithmetic/middle-school/core-calculations?kind=formula-comprehensive" },
  { grade: "중3", name: "인수분해: 공통인수", title: "인수분해: 공통인수", route: "/arithmetic/middle-school/factorization?kind=common-factor" },
  { grade: "중3", name: "인수분해: 여러 문자", title: "인수분해: 여러 문자", route: "/arithmetic/middle-school/factorization?kind=multiple-variables" },
  { grade: "중3", name: "인수분해: 두 항씩 묶기", title: "인수분해: 두 항씩 묶기", route: "/arithmetic/middle-school/factorization?kind=grouping" },
  { grade: "중3", name: "인수분해: 완전제곱식", title: "인수분해: 완전제곱식", route: "/arithmetic/middle-school/factorization?kind=perfect-square" },
  { grade: "중3", name: "인수분해: 제곱의 차", title: "인수분해: 제곱의 차", route: "/arithmetic/middle-school/factorization?kind=difference-squares" },
  { grade: "중3", name: "인수분해: 일반 이차삼항식", title: "인수분해: 일반 이차삼항식", route: "/arithmetic/middle-school/factorization?kind=nonmonic-trinomial" },
  { grade: "중3", name: "인수분해: 세 문자식", title: "인수분해: 세 문자식", route: "/arithmetic/middle-school/factorization?kind=three-variables" },
  { grade: "중3", name: "인수분해: 3차식 공통인수", title: "인수분해: 3차식 공통인수", route: "/arithmetic/middle-school/factorization?kind=cubic-common" },


  { grade: "중3", name: "인수분해: 식 정리 후 인수분해", title: "인수분해: 식 정리 후 인수분해", route: "/arithmetic/middle-school/factorization?kind=normalize-first" },
  { grade: "중3", name: "인수분해 종합", title: "인수분해 종합", route: "/arithmetic/middle-school/factorization?kind=comprehensive" },
  { grade: "중3", name: "이차방정식: 제곱근·완전제곱", title: "이차방정식: 제곱근·완전제곱", route: "/arithmetic/middle-school/quadratic-equations?kind=roots-and-squares" },
  { grade: "중3", name: "이차방정식: 기본·인수분해", title: "이차방정식: 기본·인수분해", route: "/arithmetic/middle-school/quadratic-equations?kind=factorization" },
  { grade: "중3", name: "이차방정식: 근의 공식", title: "이차방정식: 근의 공식", route: "/arithmetic/middle-school/quadratic-equations?kind=quadratic-formula" },
  { grade: "중3", name: "이차방정식: 식 정리 후 풀기", title: "이차방정식: 식 정리 후 풀기", route: "/arithmetic/middle-school/quadratic-equations?kind=normalize-and-solve" },
  { grade: "중3", name: "이차방정식 활용 계산", title: "이차방정식 활용 계산", route: "/arithmetic/middle-school/quadratic-equations?kind=applications" },
  { grade: "중3", name: "이차방정식 종합", title: "이차방정식 종합", route: "/arithmetic/middle-school/quadratic-equations?kind=comprehensive" },
  { grade: "중3", name: "이차함수", title: "이차함수", route: "/arithmetic/middle-school/quadratic-functions?kind=comprehensive" },
  { grade: "중3", name: "삼각비의 값과 특수각", title: "삼각비의 값과 특수각", route: "/arithmetic/middle-school/trigonometry?kind=ratios" },
  { grade: "중3", name: "삼각비: 특수각 계산", title: "삼각비: 특수각 계산", route: "/arithmetic/middle-school/trigonometry?kind=special-angles" },
  { grade: "중3", name: "삼각비: 변의 길이 계산", title: "삼각비: 변의 길이 계산", route: "/arithmetic/middle-school/trigonometry?kind=side-lengths" },
  { grade: "중3", name: "삼각비 계산 종합", title: "삼각비 계산 종합", route: "/arithmetic/middle-school/trigonometry?kind=comprehensive" },
  { grade: "중3", name: "원주각과 각의 응용", title: "원주각과 각의 응용", route: "/arithmetic/middle-school/circle-properties?kind=inscribed-angles" },
  { grade: "중3", name: "원의 성질: 사각형과 접선의 각", title: "원의 성질: 사각형과 접선의 각", route: "/arithmetic/middle-school/circle-properties?kind=angle-applications" },
  { grade: "중3", name: "원의 성질: 접선과 현의 길이", title: "원의 성질: 접선과 현의 길이", route: "/arithmetic/middle-school/circle-properties?kind=circle-lengths" },
  { grade: "중3", name: "원의 성질 계산 종합", title: "원의 성질 계산 종합", route: "/arithmetic/middle-school/circle-properties?kind=comprehensive" },
  { grade: "중3", name: "통계: 산포도 계산", title: "통계: 산포도 계산", route: "/arithmetic/middle-school/statistics?kind=dispersion" },
  { grade: "중3", name: "사분위수와 상자그림 계산", title: "사분위수와 상자그림 계산", route: "/arithmetic/middle-school/curriculum-calculations?kind=quartiles-boxplot" },
  { grade: "중3", name: "대푯값과 산포도 계산 종합", title: "대푯값과 산포도 계산 종합", route: "/arithmetic/middle-school/statistics?kind=comprehensive" },
]
  .filter(({ route }) => route !== null && !mergedMiddleSchoolRoutes.has(route))
  .map((worksheet) => {
    const combinedTitle = worksheet.route ? combinedMiddleSchoolTitles[worksheet.route] : undefined;
    return combinedTitle
      ? { ...worksheet, name: combinedTitle, title: combinedTitle }
      : worksheet;
  });

export const highSchoolWorksheetCatalog: ArithmeticWorksheet[] = [
  { grade: "공수1", name: "다항식의 연산", title: "다항식의 연산", route: "/arithmetic/high-school/polynomial-add-subtract" },
  { grade: "공수1", name: "다항식의 나눗셈·조립제법", title: "다항식의 나눗셈·조립제법", route: "/arithmetic/high-school/polynomial-division-remainder" },
  { grade: "공수1", name: "항등식과 나머지정리", title: "항등식과 나머지정리", route: "/arithmetic/high-school/polynomial-identities-remainders" },
  { grade: "공수1", name: "세제곱의 합·차 인수분해", title: "세제곱의 합·차 인수분해", route: "/arithmetic/high-school/cubic-sum-difference-factorization" },
  { grade: "공수1", name: "고차식·대칭식 인수분해", title: "고차식·대칭식 인수분해", route: "/arithmetic/high-school/advanced-factorization" },
  { grade: "공수1", name: "분수식의 계산", title: "분수식의 계산", route: "/arithmetic/high-school/factorization-rational" },
  { grade: "공수1", name: "복소수", title: "복소수", route: "/arithmetic/high-school/complex-numbers" },
  { grade: "공수1", name: "지수와 근호", title: "지수와 근호", route: "/arithmetic/high-school/exponents-radicals" },
  { grade: "공수1", name: "이차방정식: 판별식·근과 계수", title: "이차방정식: 판별식·근과 계수", route: "/arithmetic/high-school/quadratic-root-relations" },
  { grade: "공수1", name: "이차방정식과 이차함수", title: "이차방정식과 이차함수", route: "/arithmetic/high-school/quadratic-function-relations" },
  { grade: "공수1", name: "연립이차방정식", title: "연립이차방정식", route: "/arithmetic/high-school/simultaneous-quadratic-equations" },
  { grade: "공수1", name: "삼차방정식과 사차방정식", title: "삼차방정식과 사차방정식", route: "/arithmetic/high-school/cubic-quartic-equations" },
  { grade: "공수1", name: "유리·무리·절댓값 방정식", title: "유리·무리·절댓값 방정식", route: "/arithmetic/high-school/equation-transformations" },
  { grade: "공수1", name: "연립·절댓값·이차부등식", title: "연립·절댓값·이차부등식", route: "/arithmetic/high-school/inequality-intervals" },
  { grade: "공수1", name: "경우의 수·순열·조합", title: "경우의 수·순열·조합", route: "/arithmetic/high-school/permutations-combinations" },
  { grade: "공수1", name: "행렬의 뜻과 기본 연산", title: "행렬의 뜻과 기본 연산", route: "/arithmetic/high-school/matrices" },
  { grade: "공수2", name: "좌표와 직선의 방정식", title: "좌표와 직선의 방정식", route: "/arithmetic/high-school/coordinate-lines" },
  { grade: "공수2", name: "원의 방정식", title: "원의 방정식", route: "/arithmetic/high-school/circle-equations" },
  { grade: "공수2", name: "집합과 명제", title: "집합과 명제", route: "/arithmetic/high-school/sets-propositions" },
  { grade: "공수2", name: "합성함수와 역함수", title: "합성함수와 역함수", route: "/arithmetic/high-school/function-transformations" },
  { grade: "공수2", name: "유리함수와 무리함수", title: "유리함수와 무리함수", route: "/arithmetic/high-school/rational-radical-functions" },
  { grade: "대수", name: "로그의 값과 성질", title: "로그의 값과 성질", route: "/arithmetic/high-school/logarithms" },
  { grade: "대수", name: "지수함수와 로그함수의 그래프·활용", title: "지수함수와 로그함수의 그래프·활용", route: "/arithmetic/high-school/exponential-log-functions" },
  { grade: "대수", name: "지수·로그 방정식", title: "지수·로그 방정식", route: "/arithmetic/high-school/exponential-log-equations" },
  { grade: "대수", name: "지수·로그 부등식", title: "지수·로그 부등식", route: "/arithmetic/high-school/exponential-log-inequalities" },
  { grade: "대수", name: "일반각·호도법·부채꼴", title: "일반각·호도법·부채꼴", route: "/arithmetic/high-school/radian-measure" },
  { grade: "대수", name: "삼각함수의 값과 관계", title: "삼각함수의 값과 관계", route: "/arithmetic/high-school/trigonometric-values" },
  { grade: "대수", name: "삼각함수 그래프의 성질", title: "삼각함수 그래프의 성질", route: "/arithmetic/high-school/trigonometric-graphs" },
  { grade: "대수", name: "삼각방정식·부등식", title: "삼각방정식·부등식", route: "/arithmetic/high-school/trigonometric-equations" },
  { grade: "대수", name: "사인법칙과 코사인법칙", title: "사인법칙과 코사인법칙", route: "/arithmetic/high-school/sine-cosine-laws" },
  { grade: "대수", name: "등차수열과 등비수열", title: "등차수열과 등비수열", route: "/arithmetic/high-school/sequences" },
  { grade: "대수", name: "등비수열의 활용", title: "등비수열의 활용", route: "/arithmetic/high-school/financial-sequences" },
  { grade: "대수", name: "시그마와 점화식", title: "시그마와 점화식", route: "/arithmetic/high-school/sigma-recurrence" },
  { grade: "대수", name: "수학적 귀납법", title: "수학적 귀납법", route: "/arithmetic/high-school/mathematical-induction" },
  { grade: "미적1", name: "함수의 극한과 연속", title: "함수의 극한과 연속", route: "/arithmetic/high-school/limits-continuity" },
  { grade: "미적1", name: "다항함수의 미분", title: "다항함수의 미분", route: "/arithmetic/high-school/derivative-practice" },
  { grade: "미적1", name: "미분의 활용", title: "미분의 활용", route: "/arithmetic/high-school/derivative-applications" },
  { grade: "미적1", name: "평균값정리", title: "평균값정리", route: "/arithmetic/high-school/mean-value-theorem" },
  { grade: "미적1", name: "다항함수의 적분", title: "다항함수의 적분", route: "/arithmetic/high-school/polynomial-integrals" },
  { grade: "미적2", name: "수열의 극한과 급수", title: "수열의 극한과 급수", route: "/arithmetic/high-school/sequence-limits-series" },
  { grade: "미적2", name: "삼각함수의 덧셈정리와 합·곱 변환", title: "삼각함수의 덧셈정리와 합·곱 변환", route: "/arithmetic/high-school/trigonometric-addition" },
  { grade: "미적2", name: "지수·로그함수 미분", title: "지수·로그함수 미분", route: "/arithmetic/high-school/exponential-log-derivatives" },
  { grade: "미적2", name: "삼각함수의 미분", title: "삼각함수의 미분", route: "/arithmetic/high-school/trigonometric-derivatives" },
  { grade: "미적2", name: "sec·csc·cot 미분", title: "sec·csc·cot 미분", route: "/arithmetic/high-school/trigonometric-derivatives-2" },
  { grade: "미적2", name: "매개변수·음함수·역함수 미분", title: "매개변수·음함수·역함수 미분", route: "/arithmetic/high-school/advanced-differentiation" },
  { grade: "미적2", name: "이계도함수·변곡점·그래프 개형", title: "이계도함수·변곡점·그래프 개형", route: "/arithmetic/high-school/second-derivative-applications" },
  { grade: "미적2", name: "여러 함수의 부정적분", title: "여러 함수의 부정적분", route: "/arithmetic/high-school/transcendental-integrals" },
  { grade: "미적2", name: "치환적분과 부분적분", title: "치환적분과 부분적분", route: "/arithmetic/high-school/integration-techniques" },
  { grade: "미적2", name: "정적분 계산", title: "정적분 계산", route: "/arithmetic/high-school/definite-integrals" },
  { grade: "미적2", name: "정적분의 활용", title: "정적분의 활용", route: "/arithmetic/high-school/definite-integral-applications" },
  { grade: "미적2", name: "곡선의 길이", title: "곡선의 길이", route: "/arithmetic/high-school/arc-length" },
  { grade: "미적2", name: "회전체의 부피", title: "회전체의 부피", route: "/arithmetic/high-school/solids-of-revolution" },
  { grade: "기하", name: "이차곡선의 방정식", title: "이차곡선의 방정식", route: "/arithmetic/high-school/conic-sections" },
  { grade: "기하", name: "이차곡선의 접선", title: "이차곡선의 접선", route: "/arithmetic/high-school/conic-transformations-tangents" },
  { grade: "기하", name: "평면벡터의 연산", title: "평면벡터의 연산", route: "/arithmetic/high-school/plane-vectors" },
  { grade: "기하", name: "벡터의 내적과 정사영", title: "벡터의 내적과 정사영", route: "/arithmetic/high-school/vector-projections" },
  { grade: "기하", name: "도형과 벡터", title: "도형과 벡터", route: "/arithmetic/high-school/vector-geometry" },
  { grade: "기하", name: "공간도형의 위치 관계와 정사영", title: "공간도형의 위치 관계와 정사영", route: "/arithmetic/high-school/space-geometry-projections" },
  { grade: "기하", name: "공간좌표", title: "공간좌표", route: "/arithmetic/high-school/space-coordinates" },
  { grade: "확통", name: "순열의 활용과 중복조합", title: "순열의 활용과 중복조합", route: "/arithmetic/high-school/combinations" },
  { grade: "확통", name: "이항정리", title: "이항정리", route: "/arithmetic/high-school/binomial-theorem" },
  { grade: "확통", name: "확률의 계산", title: "확률의 계산", route: "/arithmetic/high-school/probability-rules" },
  { grade: "확통", name: "전체확률·베이즈 정리", title: "전체확률·베이즈 정리", route: "/arithmetic/high-school/probability-rules-advanced" },
  { grade: "확통", name: "이산확률분포와 이항분포", title: "이산확률분포와 이항분포", route: "/arithmetic/high-school/probability-distributions" },
  { grade: "확통", name: "정규분포의 계산", title: "정규분포의 계산", route: "/arithmetic/high-school/normal-distributions" },
  { grade: "확통", name: "통계적 추정", title: "통계적 추정", route: "/arithmetic/high-school/statistical-inference" },
];

export const stemWorksheetCatalog: ArithmeticWorksheet[] = [
  { grade: "이공계 기초", name: "복소수의 극형식·오일러 공식", title: "복소수의 극형식·오일러 공식", route: "/arithmetic/stem/foundation?kind=complex-polar" },
  { grade: "이공계 기초", name: "행렬·행렬식·가우스 소거", title: "행렬·행렬식·가우스 소거", route: "/arithmetic/stem/foundation?kind=matrix-systems" },
  { grade: "이공계 기초", name: "벡터공간·기저·고유값 입문", title: "벡터공간·기저·고유값 입문", route: "/arithmetic/stem/foundation?kind=vector-spaces-rank" },
  { grade: "이공계 기초", name: "편미분·그래디언트 입문", title: "편미분·그래디언트 입문", route: "/arithmetic/stem/foundation?kind=partial-derivatives" },
  { grade: "이공계 기초", name: "이중적분·좌표변환 입문", title: "이중적분·좌표변환 입문", route: "/arithmetic/stem/foundation?kind=multiple-integrals" },
  { grade: "이공계 기초", name: "미분방정식 입문", title: "미분방정식 입문", route: "/arithmetic/stem/foundation?kind=first-order-ode" },
];

export const learningWorksheetCatalog = [
  ...arithmeticWorksheetCatalog,
  ...middleSchoolWorksheetCatalog,
  ...highSchoolWorksheetCatalog,
  ...stemWorksheetCatalog,
];

export const raceReadyWorksheets = arithmeticWorksheetCatalog.filter(
  (worksheet): worksheet is ArithmeticWorksheet & { route: string } => Boolean(worksheet.route?.startsWith("/arithmetic/")),
);

export function raceWorksheetByRoute(route: string) {
  return raceReadyWorksheets.find((worksheet) => worksheet.route === route) ?? null;
}
