export function targetQuestion(label: string) {
  const trimmed = label.trim();
  if (/[?？]$/.test(trimmed)) return trimmed;
  const last = trimmed.at(-1);
  if (!last) throw new Error("Worksheet question requires a non-empty label");
  const code = last.charCodeAt(0);
  const hasFinalConsonant = code >= 0xac00 && code <= 0xd7a3
    ? (code - 0xac00) % 28 !== 0
    : false;
  return `${trimmed}${hasFinalConsonant ? "은" : "는"}?`;
}

export function worksheetQuestionForLabel(label: string) {
  if (/좌표와 사분면/.test(label)) return "점이 속한 사분면은?";
  if (/좌표축 위의 점/.test(label)) return "점이 놓인 좌표축은?";
  if (/정비례 상수|반비례 상수/.test(label)) return "상수 $a$는?";
  if (/정비례의 값|반비례의 값/.test(label)) return "$y$의 값은?";
  if (/표의 빈칸/.test(label)) return "빈칸에 들어갈 수는?";
  if (/함숫값에서 x/.test(label)) return "$x$는?";
  if (/함숫값/.test(label)) return "함숫값은?";
  if (/인수분해/.test(label)) return "인수분해한 식은?";
  if (/전개/.test(label)) return "전개한 식은?";
  if (/꼭짓점.*대칭축|대칭축.*꼭짓점/.test(label)) return "꼭짓점과 대칭축은?";
  if (/꼭짓점형|완전제곱/.test(label)) return "꼭짓점형은?";
  if (/그래프와 연립방정식/.test(label)) return "$(x, y)$는?";
  if (/방정식|해 구하기|근의 공식/.test(label)) return "해는?";
  if (/부등식/.test(label)) return "해는?";
  if (/도함수|미분/.test(label)) return "도함수는?";
  if (/부정적분/.test(label)) return "부정적분한 결과는?";
  if (/정적분/.test(label)) return "정적분 값은?";
  if (/적분/.test(label)) return "적분한 결과는?";
  if (/두 점으로 일차함수 구하기/.test(label)) return "일차함수의 식은?";
  if (/한 점을 지나는 평행선/.test(label)) return "직선의 식은?";
  if (/두 직선의 교점 조건/.test(label)) return "조건을 만족하는 미지수는?";
  if (/기울기/.test(label)) return "기울기는?";
  if (/절편/.test(label)) return "절편은?";
  if (/교점/.test(label)) return "교점은?";
  if (/평균/.test(label)) return "평균은?";
  if (/중앙값/.test(label)) return "중앙값은?";
  if (/최빈값/.test(label)) return "최빈값은?";
  if (/제1사분위수/.test(label)) return "제1사분위수는?";
  if (/제3사분위수/.test(label)) return "제3사분위수는?";
  if (/사분위범위/.test(label)) return "사분위범위는?";
  if (/다섯 수 요약/.test(label)) return "다섯 수 요약은?";
  if (/두 상자그림.*산포도 비교/.test(label)) return "사분위범위가 더 큰 자료는?";
  if (/범위/.test(label)) return "범위는?";
  if (/분산/.test(label)) return "분산은?";
  if (/표준편차/.test(label)) return "표준편차는?";
  if (/확률/.test(label)) return "확률은?";
  if (/합의 법칙|곱의 법칙|경우의 수|두 단계 선택/.test(label)) return "경우의 수는?";
  if (/직각삼각형 판별/.test(label)) return "직각삼각형인가?";
  if (/다각형의 내각의 합/.test(label)) return "내각의 합은?";
  if (/다각형의 대각선/.test(label)) return "대각선의 개수는?";
  if (/부채꼴의 호와 넓이/.test(label)) return "호의 길이와 넓이는?";
  if (/구의 부피와 겉넓이/.test(label)) return "부피와 겉넓이는?";
  if (/둘레의 길이의 비/.test(label)) return "둘레의 길이의 비는?";
  if (/넓이의 비/.test(label)) return "넓이의 비는?";
  if (/닮음비/.test(label)) return "닮음비는?";
  if (/평행선과 선분의 비/.test(label)) return "선분의 길이는?";
  if (/외심과 꼭짓점의 거리/.test(label)) return "외심에서 꼭짓점까지의 거리는?";
  if (/내심과 각의 이등분/.test(label)) return "각의 크기는?";
  if (/삼각형의 무게중심/.test(label)) return "선분의 길이는?";
  if (/원주각|중심각|맞꼭지각|동위각|엇각|삼각형의 내각|정다각형의 한 내각|정다각형의 한 외각|이등변삼각형의 각|삼각형의 외각|평행사변형의 각|접선과 현이 이루는 각|원에 내접하는 사각형/.test(label)) return "각의 크기는?";
  if (/한 점에서 그은 두 접선/.test(label)) return "접선의 길이는?";
  if (/중심과 현의 길이/.test(label)) return "현의 길이는?";
  if (/현에서 중심까지의 거리/.test(label)) return "중심까지의 거리는?";
  if (/호의 크기 합산/.test(label)) return "호의 크기는?";
  if (/거리/.test(label)) return "거리는?";
  if (/길이|대응변|중점연결선|중점연결정리/.test(label)) return "길이는?";
  if (/넓이/.test(label)) return "넓이는?";
  if (/부피/.test(label)) return "부피는?";
  if (/좌표/.test(label)) return "좌표는?";
  if (/식 구하기|식 결정|방정식 구하기/.test(label)) return "구하는 식은?";
  if (/최댓값.*최솟값|최솟값.*최댓값/.test(label)) return "최댓값과 최솟값은?";
  if (/최댓값/.test(label)) return "최댓값은?";
  if (/최솟값/.test(label)) return "최솟값은?";
  if (/계수/.test(label)) return "계수의 값은?";
  if (/나머지/.test(label)) return "나머지는?";
  if (/값|계산|연산|덧셈|뺄셈|곱셈|나눗셈|정리|약분|근호|제곱근|복소수|행렬|다항식|다항함수|유리식/.test(label)) return "계산 결과는?";
  return targetQuestion(label);
}
