const lessons={ko:[['학교','친구','하늘','바다','나무','사과','구름','마음','고양이','무지개'],['나는 책을 읽어요.','친구와 함께 걸어요.','맑은 하늘을 보아요.','오늘도 힘차게 시작해요.','고운 말을 사용해요.','천천히 또박또박 써요.','우리 반은 서로 도와요.','약속 시간을 잘 지켜요.','공원에서 나무를 보았어요.','웃으면 기분이 좋아져요.'],['따뜻한 햇살이 교실 창문으로 들어옵니다.','우리는 서로의 생각을 귀 기울여 듣습니다.','모르는 문제는 차근차근 다시 생각해 봅니다.','작은 친절이 친구의 하루를 환하게 만듭니다.','매일 꾸준히 연습하면 실력이 자라납니다.','도서관에서는 작은 목소리로 이야기합니다.','푸른 숲에는 다양한 동물과 식물이 삽니다.','안전한 길을 살피고 횡단보도를 건넙니다.','실수해도 포기하지 않고 다시 도전합니다.','오늘 배운 내용을 내 말로 설명해 봅니다.']],en:[['school','friend','happy','apple','green','music','family','water','smile','morning'],['I like my school.','We play together.','The sky is blue.','This is my pencil.','I can read a book.','Have a nice day!','My friend is kind.','We help each other.','The cat is sleeping.','I love my family.'],['I walk to school with my best friend.','We listen carefully and share our ideas.','Practice helps me become a better learner.','The little bird sings in the green tree.','I always try again when something is hard.','Please put your books on the classroom shelf.','A bright rainbow appeared after the rain.','Our class works together as a great team.','Reading a good story can take us anywhere.','Today is a wonderful day to learn something new.']]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={lang:'ko',level:0,index:0,start:0,typed:0,correct:0,streak:0,speeds:[],sound:true,locked:false};
const fingerNames={lp:'왼손 새끼손가락',lr:'왼손 약손가락',lm:'왼손 가운데손가락',li:'왼손 검지',ri:'오른손 검지',rm:'오른손 가운데손가락',rr:'오른손 약손가락',rp:'오른손 새끼손가락','rr-rp':'오른손의 편한 손가락'};
const keyboardRows=[[['Q','ㅂ','lp'],['W','ㅈ','lr'],['E','ㄷ','lm'],['R','ㄱ','li'],['T','ㅅ','li'],['Y','ㅛ','ri'],['U','ㅕ','ri'],['I','ㅑ','rm'],['O','ㅐ','rr'],['P','ㅔ','rr-rp']],[['A','ㅁ','lp'],['S','ㄴ','lr'],['D','ㅇ','lm'],['F','ㄹ','li'],['G','ㅎ','li'],['H','ㅗ','ri'],['J','ㅓ','ri'],['K','ㅏ','rm'],['L','ㅣ','rr']],[['Shift','⇧ Shift','lp','shift-left'],['Z','ㅋ','lp'],['X','ㅌ','lr'],['C','ㅊ','lm'],['V','ㅍ','li'],['B','ㅠ','li'],['N','ㅜ','ri'],['M','ㅡ','ri'],['Shift','⇧ Shift','rp','shift-right']]];
const baseGuideOrder=['f','j','d','k','s','l','a','g','h','r','u','e','i','w','o','q','p','t','y','v','m','c','x','z','b','n'];
const koreanShiftGuide=['shift-right+q','shift-right+w','shift-right+e','shift-right+r','shift-right+t','shift-left+o','shift-left+p'];
const englishShiftGuide=['shift-right+q','shift-left+p'];
let guideLang='ko',guideIndex=0,virtualShift='';
const koInitial=['r','R','s','e','E','f','a','q','Q','t','T','d','w','W','c','z','x','v','g'];
const koMedial=['k','o','i','O','j','p','u','P','h','hk','ho','hl','y','n','nj','np','nl','b','m','ml','l'];
const koFinal=['','r','R','rt','s','sw','sg','e','f','fr','fa','fq','ft','fx','fv','fg','a','q','qt','t','T','d','w','c','z','x','v','g'];
const codeChars={Space:' ',Period:'.',Comma:',',Slash:'/',Semicolon:';',Quote:"'",Minus:'-',Equal:'=',BracketLeft:'[',BracketRight:']'};
let forcedKeyProgress=0;
const input=$('#typingInput'),prompt=$('#prompt'),feedback=$('#feedback');
function keySequenceForChar(char){const code=char.charCodeAt(0);if(state.lang==='ko'&&code>=0xAC00&&code<=0xD7A3){const offset=code-0xAC00,initial=Math.floor(offset/588),medial=Math.floor((offset%588)/28),final=offset%28;return koInitial[initial]+koMedial[medial]+koFinal[final]}return char}
function targetKeySequence(){return [...target()].map(keySequenceForChar).join('')}
function completedTargetPrefix(progress){let used=0,result='';for(const char of [...target()]){const length=keySequenceForChar(char).length;if(used+length>progress)break;used+=length;result+=char}return result}
function physicalCharacter(event){if(/^Key[A-Z]$/.test(event.code)){const letter=event.code.slice(3).toLowerCase();return event.shiftKey?letter.toUpperCase():letter}if(event.code==='Space')return ' ';const plain=codeChars[event.code];if(!plain)return '';if(!event.shiftKey)return plain;return {'.':'>',',':'<','/':'?',';':':',"'":'"','-':'_','=':'+','[':'{',']':'}'}[plain]||plain}
function resetForcedInput(){forcedKeyProgress=0}
function buildKeyboard(){const box=$('#keyboard');box.innerHTML=keyboardRows.map(row=>`<div class="key-row">${row.map(([en,ko,f,code])=>`<button type="button" class="key ${(en==='F'||en==='J')?'home-key':''} ${en==='Shift'?'shift-key':''}" data-code="${code||en.toLowerCase()}" data-finger="${f}">${en==='Shift'?'⇧ Shift':guideLang==='ko'?ko:en}</button>`).join('')}</div>`).join('');box.querySelectorAll('.key').forEach(k=>k.addEventListener('click',()=>{const code=k.dataset.code;if(code.startsWith('shift-')){virtualShift=code.slice(6);return}checkGuide(code,virtualShift);virtualShift=''}));showGuide()}
function guideOrder(){return baseGuideOrder.concat(guideLang==='ko'?koreanShiftGuide:englishShiftGuide)}
function guideTarget(){const order=guideOrder();return order[guideIndex%order.length]}
function guideCombo(){const target=guideTarget();if(!target.includes('+'))return null;const [shiftCode,letter]=target.split('+');return{side:shiftCode.slice(6),shiftCode,letter}}
function activateFinger(finger){finger.split('-').forEach(code=>$(`.finger[data-finger="${code}"]`)?.classList.add('active'))}
function showGuide(){virtualShift='';$$('.key,.finger').forEach(x=>x.classList.remove('active'));const combo=guideCombo();if(combo){const shiftEl=$(`.key[data-code="${combo.shiftCode}"]`),letterEl=$(`.key[data-code="${combo.letter}"]`);shiftEl.classList.add('active');letterEl.classList.add('active');activateFinger(shiftEl.dataset.finger);activateFinger(letterEl.dataset.finger);const shiftedKorean={q:'ㅃ',w:'ㅉ',e:'ㄸ',r:'ㄲ',t:'ㅆ',o:'ㅒ',p:'ㅖ'};const output=guideLang==='ko'?shiftedKorean[combo.letter]:combo.letter.toUpperCase();$('#fingerBadge').textContent=`${combo.side==='left'?'왼쪽':'오른쪽'} Shift + ${letterEl.textContent}`;$('#guideKey').textContent=output;$('#guideMessage').innerHTML=`${combo.side==='left'?'왼쪽':'오른쪽'} <b>Shift</b>를 누른 채 <b>${letterEl.textContent}</b> 키를 눌러 <b>${output}</b>을 입력하세요.`}else{const keyEl=$(`.key[data-code="${guideTarget()}"]`);if(!keyEl)return;keyEl.classList.add('active');const finger=keyEl.dataset.finger;activateFinger(finger);$('#fingerBadge').textContent=fingerNames[finger];$('#guideKey').textContent=keyEl.textContent;$('#guideMessage').innerHTML=finger==='rr-rp'?`약지나 새끼손가락 중 편한 손가락으로 <b>${keyEl.textContent}</b> 키를 눌러 보세요.`:`파란색으로 표시된 손가락으로 <b>${keyEl.textContent}</b> 키를 눌러 보세요.`}const order=guideOrder();$('#guideCount').textContent=`${guideIndex} / ${order.length}`;$('#guideBar').style.width=`${guideIndex/order.length*100}%`}
function checkGuide(code,shiftSide=''){const combo=guideCombo(),correct=combo?code===combo.letter&&shiftSide===combo.side:code===guideTarget();if(!correct)return ping(false);ping(true);guideIndex++;if(guideIndex>=guideOrder().length){$('#guideCount').textContent='완료!';$('#guideBar').style.width='100%';$('#guideMessage').innerHTML='<b>모든 글자 자리와 Shift 조합을 익혔어요!</b> 이제 낱말을 연습해요.';setTimeout(openPractice,650)}else showGuide()}
function openPractice(){input.value='';$('#fingerGuide').hidden=true;$('.practice').hidden=false;setup()}
function openGuide(){guideIndex=0;$('.practice').hidden=true;$('#resultCard').hidden=true;$('#fingerGuide').hidden=false;buildKeyboard()}
function key(){return `typing-best-${state.lang}-${state.level}`}
function target(){return lessons[state.lang][state.level][state.index]}
function chars(s){return [...s]}
function renderPrompt(){const typed=chars(input.value),goal=chars(target());prompt.innerHTML=goal.map((c,i)=>`<span class="${i>=typed.length?'rest':typed[i]===c?'done':'wrong'}">${c===' '?'&nbsp;':c.replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}</span>`).join('')}
function stats(){const elapsed=Math.max((Date.now()-state.start)/60000,1/60);const speed=state.start?Math.round(state.typed/elapsed):0;const accuracy=state.typed?Math.round(state.correct/state.typed*100):100;$('#speed').textContent=speed;$('#accuracy').textContent=accuracy;$('#streak').textContent=state.streak;return{speed,accuracy}}
function setup(){state.index=0;state.start=0;state.typed=0;state.correct=0;state.streak=0;state.speeds=[];state.locked=false;input.value='';input.disabled=false;$('.practice').hidden=false;$('#resultCard').hidden=true;showItem();stats();setTimeout(()=>input.focus(),50)}
function showItem(){input.value='';resetForcedInput();input.classList.remove('error');feedback.className='feedback';feedback.textContent='한/영 키를 바꾸지 않아도 바로 입력할 수 있어요.';$('#stepLabel').textContent=`${state.index+1} / 10`;$('#bestLabel').textContent=`최고 ${localStorage.getItem(key())||0}타/분`;$('#progressBar').style.width=`${(state.index+1)*10}%`;renderPrompt()}
function ping(ok){if(!state.sound)return;try{const ctx=new AudioContext(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=ok?620:190;g.gain.value=.045;o.connect(g);g.connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.09);o.stop(ctx.currentTime+.1)}catch{}}
function complete(){if(state.locked)return;state.locked=true;const current=target(),given=input.value;if(given!==current){input.classList.add('error');feedback.className='feedback bad';feedback.textContent='빨간 글자를 고쳐 보세요.';ping(false);state.locked=false;return}const result=stats();state.streak++;state.speeds.push(result.speed);feedback.className='feedback good';feedback.textContent='정확해요! 참 잘했어요.';ping(true);setTimeout(()=>{state.index++;state.locked=false;if(state.index>=10)finish();else showItem()},420)}
function finish(){const r=stats(),average=Math.round(state.speeds.reduce((a,b)=>a+b,0)/Math.max(state.speeds.length,1)),best=Math.max(Number(localStorage.getItem(key())||0),average);localStorage.setItem(key(),best);input.disabled=true;$('.practice').hidden=true;$('#resultCard').hidden=false;$('#resultSpeed').textContent=average;$('#resultAccuracy').textContent=`${r.accuracy}%`;$('#resultTitle').textContent=r.accuracy>=95?'정확하고 멋져요!':'끝까지 해냈어요!'}
input.addEventListener('input',()=>{if(!state.start)state.start=Date.now();const prev=state.typed;const written=chars(input.value);state.typed+=Math.max(0,written.length-prev);if(written.length>prev){const goal=chars(target());for(let i=prev;i<written.length;i++)if(written[i]===goal[i])state.correct++}renderPrompt();stats();input.classList.toggle('error',written.some((c,i)=>c!==chars(target())[i]));if(input.value===target())complete()});
input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();input.value===target()?complete():skip();return}if(e.ctrlKey||e.altKey||e.metaKey)return;if(e.key==='Backspace'){e.preventDefault();forcedKeyProgress=Math.max(0,forcedKeyProgress-1);input.value=completedTargetPrefix(forcedKeyProgress);input.classList.remove('error');renderPrompt();return}const pressed=physicalCharacter(e);if(!pressed)return;e.preventDefault();if(!state.start)state.start=Date.now();state.typed++;const expected=targetKeySequence()[forcedKeyProgress];if(pressed===expected){state.correct++;forcedKeyProgress++;input.value=completedTargetPrefix(forcedKeyProgress);input.classList.remove('error');feedback.className='feedback';feedback.textContent='좋아요. 그대로 이어서 입력하세요!';renderPrompt();stats();if(forcedKeyProgress===targetKeySequence().length)complete()}else{input.classList.add('error');feedback.className='feedback bad';feedback.textContent=`다른 키예요. ${state.lang==='ko'?'한글':'영어'} 모드 키 위치대로 눌러 보세요.`;renderPrompt();stats();ping(false)}});
function skip(){state.streak=0;state.index=(state.index+1)%10;showItem();stats();input.focus()}
$$('[data-language]').forEach(b=>b.addEventListener('click',()=>{state.lang=b.dataset.language;$$('[data-language]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});setup()}));
$('#levelButton').addEventListener('click',()=>{const p=$('#levelPanel'),open=p.hidden;p.hidden=!open;$('#levelButton').setAttribute('aria-expanded',open)});
$$('[data-level]').forEach(b=>b.addEventListener('click',()=>{state.level=Number(b.dataset.level);$$('[data-level]').forEach(x=>x.classList.toggle('active',x===b));$('#levelButton').innerHTML=`<span>${state.level+1}단계</span><strong>${['낱말','짧은 문장','긴 문장'][state.level]}</strong><span aria-hidden="true">⌄</span>`;$('#levelPanel').hidden=true;$('#levelButton').setAttribute('aria-expanded','false');setup()}));
$('#soundButton').addEventListener('click',e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'소리 켬':'소리 끔';e.currentTarget.setAttribute('aria-pressed',state.sound)});
$$('[data-guide-language]').forEach(b=>b.addEventListener('click',()=>{guideLang=b.dataset.guideLanguage;guideIndex=0;$$('[data-guide-language]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});buildKeyboard()}));
const heldShift={left:false,right:false};
document.addEventListener('keydown',e=>{if($('#fingerGuide').hidden||e.ctrlKey||e.altKey||e.metaKey)return;if(e.code==='ShiftLeft'){heldShift.left=true;return}if(e.code==='ShiftRight'){heldShift.right=true;return}checkGuide(e.key.toLowerCase(),heldShift.left?'left':heldShift.right?'right':'')});
document.addEventListener('keyup',e=>{if(e.code==='ShiftLeft')heldShift.left=false;if(e.code==='ShiftRight')heldShift.right=false});
$('#startWordsButton').addEventListener('click',openPractice);$('#restartButton').addEventListener('click',openGuide);$('#againButton').addEventListener('click',setup);$('#skipButton').addEventListener('click',skip);buildKeyboard();
