(() => {
    "use strict";

    // 차시 배정표. 시 본문은 poems.js, 문제 본문은 questions.js에 있고 여기서는 묶기만 한다.
    // 시 문제는 시가 데리고 있다(questions.js의 poemId). 그래서 한 시가 여러 차시에 나와도
    // 그 시를 열면 제 문제를 다 만난다.
    // 여기 wrapIds에는 시 없이 차시를 마무리하는 문제만 적는다.
    // poemIds가 비어 있는 차시는 아직 만들지 않은 차시로, 화면에서 '준비 중'으로 보인다.
    const lesson = (id, grade, title, note, poemIds, wrapIds) => ({ id, grade, title, note, poemIds, wrapIds });

    window.POETRY_LESSONS = Object.freeze([
        // ── 초3 · 시가 어떻게 생겼는지 알기 ────────────────────────────
        lesson("g3-scene", 3, "짧은 시 한 편 통째로 그리기", "장면 하나가 시 한 편이 돼요",
            ["jiyong-hosu", "jiyong-byeoltong", "taeeung-gamjakkot", "jiyong-hongsi"],
            ["scene-common"]),
        lesson("g3-repeat", 3, "되풀이", "같은 말이 왜 자꾸 나올까요",
            ["sowol-eommaya", "sowol-geumjandi", "deokchul-bompyeonji", "dongju-banditbul"],
            ["repeat-why"]),
        lesson("g3-mimetic", 3, "흉내내는 말", "소리와 모습을 글자로 옮겨요",
            ["dongju-haetbi", "dongju-chamsae", "jiyong-hongsi"],
            []),
        lesson("g3-calling", 3, "부르는 말", "대답 없는 것에게 말을 걸어요",
            ["folk-saeya", "folk-dara", "folk-dukkeobi", "sowol-eommaya"],
            ["calling-no-answer"]),
        lesson("g3-asking", 3, "시로 물어보기", "묻는 말로 시작하면 함께 생각하게 돼요",
            ["rossetti-baram", "dongju-nun", "folk-eodikkaji"],
            []),

        // ── 초4 · 빗대기와 감각 ───────────────────────────────────────
        lesson("g4-simile", 4, "~같이, ~처럼", "무엇에 빗대었는지 찾아요",
            ["stevenson-geurimja", "leejanghee-bomeun", "dongju-haetbi", "stevenson-bi"],
            ["simile-mark"]),
        lesson("g4-persona", 4, "사람처럼 말하기", "사물이 사람이 되어 움직여요",
            ["dongju-bom", "dongju-jogaekkeopjil", "rossetti-baram", "deokchul-bompyeonji"],
            ["persona-what"]),
        lesson("g4-senses", 4, "오감으로 그리기", "눈·귀·코·혀·살갗으로 그린 시",
            ["rossetti-bunhong", "leebaek-jeongyasa", "dubo-chunyahuiu", "stevenson-geune"],
            ["senses-why"]),
        lesson("g4-speaker", 4, "말하는 이는 지금 어디에 있나", "시 속 사람의 자리를 찾아요",
            ["dongju-gulttuk", "kimyeongrang-omae", "jiyong-byeoltong", "dongju-jogaekkeopjil"],
            ["speaker-why"]),
        lesson("g4-bittersweet", 4, "웃긴데 왜 슬플까", "웃음 뒤에 숨은 마음",
            ["dongju-ojumssagae", "dongju-geojitburi", "dongju-chamsae", "jiyong-hongsi"],
            ["bittersweet-how"]),

        // ── 초5 · 감춰진 뜻과 짜임 ────────────────────────────────────
        lesson("g5-metaphor", 5, "빗댄 말을 감추기", "'~은 ~이다'로 곧장 말해요",
            ["manhae-narutbae", "dongju-sonyeon", "dongju-nun", "leejanghee-bomeun"],
            ["metaphor-what"]),
        lesson("g5-sound", 5, "소리가 만드는 느낌", "부드러운 소리와 센 소리",
            ["yeongrang-doldam", "dongju-bom", "kimyeongrang-omae", "dongju-haetbi"],
            ["sound-why"]),
        lesson("g5-empathy", 5, "사물이 대신 우는 것", "내 마음을 사물에 옮겨 놓아요",
            ["wangbangyeon-cheonmalli", "leegae-chokbul", "dongju-jogaekkeopjil"],
            ["empathy-how"]),
        lesson("g5-flow", 5, "처음과 끝이 어떻게 달라지나", "시가 흘러가는 길",
            ["sowol-sanyuhwa", "sowol-gaeyeoul", "dongju-saeroun-gil", "jiyong-byeoltong"],
            []),
        lesson("g5-sijo", 5, "시조의 틀", "석 줄에 담는 옛 노래",
            ["leesunsin-hansanseom", "yunseondo-ouga", "hwanghui-daechu", "leejeongbo-gukhwa"],
            ["sijo-shape"]),

        // ── 초6 · 어긋난 말과 겹친 뜻 ─────────────────────────────────
        lesson("g6-irony", 6, "속마음과 반대로 말하기", "겉말과 속말이 어긋나요",
            ["sowol-jindallae", "sowol-meonhuil", "sasol-dukkeobi"],
            ["irony-what"]),
        lesson("g6-paradox", 6, "앞뒤가 안 맞는 말", "말이 안 되는데 뜻이 통해요",
            ["manhae-bokjong", "manhae-alsu", "manhae-narutbae"],
            ["paradox-what"]),
        lesson("g6-symbol", 6, "하나가 여러 뜻", "별 하나가 여럿을 가리켜요",
            ["dongju-seosi", "yuksa-cheongpodo", "nocheonmyeong-saseum"],
            ["symbol-what"]),
        lesson("g6-contrast", 6, "맞세우기", "빛깔과 처지를 나란히 놓아요",
            ["dongju-jahwasang", "yuksa-cheongpodo", "sowol-sanyuhwa", "nocheonmyeong-saseum"],
            ["contrast-why"]),
        lesson("g6-compare", 6, "두 편 나란히 읽기", "닮은 시와 다른 시",
            ["leebangwon-hayeoga", "jeongmongju-dansimga", "sowol-jindallae", "sowol-meonhuil"],
            ["compare-how"]),
        lesson("g6-oldsong", 6, "옛 노래의 후렴과 가락", "가장 오래된 우리 노래들",
            ["goryeo-cheongsan", "goryeo-gasiri", "gojia-guji", "jiyong-hyangsu"],
            ["oldsong-why"]),

        // ── 중1 · 시인별로 묶어 읽기 ──────────────────────────────────
        // 여기서부터는 배우는 것이 아니라 시인으로 묶는다. 시험은 아는 시인의 처음 보는 시를 내니까,
        // 익숙한 시 곁에 처음 보는 시를 한 편씩 두어 그 시인의 버릇을 익히게 한다.
        lesson("m1-jiyong", 7, "정지용 다시 읽기", "아는 시인, 처음 보는 시",
            ["jiyong-yurichang", "jiyong-hyangsu", "jiyong-hosu", "jiyong-byeoltong"],
            ["jiyong-habit", "jiyong-new"]),
        lesson("m1-sowol", 7, "김소월 다시 읽기", "헤어짐 앞에서 머뭇거리는 시",
            ["sowol-ganeungil", "sowol-jeopdongsae", "sowol-jindallae", "sowol-sanyuhwa"],
            ["sowol-habit"]),
        lesson("m1-era", 7, "빼앗긴 땅에서 쓴 시", "시대를 알고 읽기",
            ["sanghwa-ppaeatgin", "yuksa-cheongpodo", "dongju-seosi"],
            ["era-how"]),
        lesson("m1-hyangga", 7, "천 년 전의 노래", "신라 향가 세 편",
            ["hyangga-jemangmaega", "hyangga-seodongyo", "hyangga-heonhwaga"],
            ["hyangga-what"]),
        lesson("m1-textbook", 7, "교과서에서 읽는 시", "본문은 교과서에서",
            ["gihyeongdo-eomma", "kimjonggil-seongtanje", "sinseokjeong-meonnara"],
            ["textbook-common"]),

        // ── 중2 ───────────────────────────────────────────────────────
        lesson("m2-manhae", 8, "한용운 다시 읽기", "어긋난 말에 담은 님",
            ["manhae-nim", "manhae-narutbae", "manhae-bokjong", "manhae-alsu"],
            ["manhae-you", "manhae-habit"]),
        lesson("m2-yuksa", 8, "이육사 다시 읽기", "벼랑 끝에서 세운 뜻",
            ["yuksa-jeoljeong", "yuksa-kkot", "yuksa-cheongpodo"],
            ["yuksa-habit"]),
        lesson("m2-yeongrang", 8, "김영랑 다시 읽기", "찬란한 슬픔의 봄",
            ["yeongrang-moran", "yeongrang-doldam", "kimyeongrang-omae"],
            ["yeongrang-habit"]),
        lesson("m2-dongju", 8, "윤동주 다시 읽기", "나를 들여다보는 시",
            ["dongju-ttodareun", "dongju-jahwasang", "dongju-seosi"],
            ["dongju-habit"]),
        lesson("m2-leaving", 8, "떠남과 돌아옴", "문턱에서 머뭇거리는 시",
            ["ojanghwan-gohyang", "yongcheol-tteonaganeun"],
            ["leaving-compare"]),
        lesson("m2-old", 8, "옛 노래 더 읽기", "시조 세 수와 고려 노래 둘",
            ["leehwang-dosan", "goryeo-dongdong", "goryeo-jeongseokga"],
            ["old-refrain-again"]),

        // ── 중3 ───────────────────────────────────────────────────────
        lesson("m3-yuksa", 9, "이육사 마지막 시들", "시간을 펼쳐 놓은 뜻",
            ["yuksa-gwangya", "yuksa-gyomok", "yuksa-jeoljeong"],
            ["yuksa-final"]),
        lesson("m3-dongju", 9, "윤동주의 부끄러움", "거울을 닦는 시",
            ["dongju-chamhoerok", "dongju-sipjaga", "dongju-swipge", "dongju-seosi"],
            ["dongju-shame"]),
        lesson("m3-sowol", 9, "김소월의 절규와 그리움", "눌러 참기와 목놓아 부르기",
            ["sowol-chohon", "sowol-sakju", "sowol-jindallae"],
            []),
        lesson("m3-modern", 9, "낯선 눈으로 본 나와 고향", "가까운 것이 낯설어질 때",
            ["leesang-geoul", "jiyong-gohyang", "inhwan-sewol"],
            ["modern-strange"]),
        lesson("m3-river", 9, "강물에 실은 마음", "흐르는 물에 얹은 뜻과 눈물",
            ["yeongro-nongae", "jisang-songin", "wangbangyeon-cheonmalli"],
            ["river-common"]),
        lesson("m3-gasa", 9, "가사와 어부의 노래", "길게 이어지는 옛 노래글",
            ["geugin-sangchun", "seondo-eobu", "jeongcheol-gwandong"],
            ["gasa-shape"]),

        // ── 고1 ───────────────────────────────────────────────────────
        lesson("h1-jiyong", 10, "정지용의 산과 겨울", "감정을 지운 자리",
            ["jiyong-bi", "jiyong-indongcha", "jiyong-jangsusan", "jiyong-yurichang"],
            ["jiyong-late"]),
        lesson("h1-two-faces", 10, "김영랑과 이육사, 다른 얼굴", "아는 이름의 낯선 시",
            ["yeongrang-dok", "yeongrang-buk", "yuksa-jayagok", "yeongrang-doldam"],
            ["two-faces"]),
        lesson("h1-dongju", 10, "윤동주, 잃어버린 것을 찾아서", "담 저쪽의 나",
            ["dongju-gil", "dongju-gan", "dongju-chamhoerok"],
            ["dongju-search"]),
        lesson("h1-leesang", 10, "이상, 낯선 시", "띄어쓰기를 없앤 까닭",
            ["leesang-ogamdo", "leesang-geoul"],
            []),
        lesson("h1-hyangga", 10, "향가 더 읽기", "열 줄 노래의 짜임",
            ["hyangga-changiparang", "hyangga-anminga", "hyangga-jemangmaega"],
            ["hyangga-ten"]),
        lesson("h1-joseon", 10, "조선의 노래", "나라의 노래와 한 사람의 노래",
            ["joseon-yongbi", "jeongcheol-samiin"],
            ["joseon-purpose"]),
        lesson("h1-textbook", 10, "교과서에서 읽는 시", "본문은 교과서에서",
            ["baekseok-yeoseung", "hyeonseung-platanus", "gwangseop-bidulgi", "hyeonggi-nakhwa"],
            ["textbook-h1-common"]),

        // ── 고2·3 · 수능 고전시가 ─────────────────────────────────────
        lesson("h2-gwandong", 11, "관동별곡 깊이 읽기", "금강산·동해·꿈",
            ["jeongcheol-gwandong-2", "jeongcheol-gwandong"],
            ["gw2-structure", "gw2-two-minds"]),
        lesson("h2-songmiin", 11, "속미인곡", "두 여인의 대화",
            ["jeongcheol-songmiin", "jeongcheol-samiin"],
            []),
        lesson("h2-gyuwon", 11, "규원가", "여인이 쓴 여인의 노래",
            ["heo-gyuwonga", "jeongcheol-samiin"],
            ["gy-author"]),
        lesson("h2-nuhang", 11, "누항사와 선상탄", "전쟁 뒤의 가사",
            ["bakinro-nuhangsa", "bakinro-seonsangtan"],
            ["gasa-late"]),
        lesson("h2-nongga", 11, "농가월령가", "열두 달 농사 노래",
            ["jeonghakyu-nongga", "goryeo-dongdong"],
            []),
        lesson("h2-sijo-1", 11, "강호와 충, 시조 읽기", "산에 살아도 마음은 임금께",
            ["leei-gosan", "seondo-manheung", "seondo-gyeonhoeyo"],
            ["sijo-gangho"]),
        lesson("h2-sijo-2", 11, "옛 시조 더 읽기", "매화와 국화, 그리고 두꺼비",
            ["minyeong-maehwasa", "leejeongbo-gukhwa", "sasol-dukkeobi"],
            []),
        lesson("h2-goryeo", 11, "고려가요 더 읽기", "이별의 세 목소리",
            ["goryeo-seogyeong", "goryeo-manjeonchun", "jeongseo-jeonggwajeong", "goryeo-gasiri"],
            []),
        lesson("h2-hansi", 11, "한시 넷", "참새와 황두, 텅 빈 성과 무궁화",
            ["jehyeon-sarihwa", "leesaek-bubyeongnu", "hwanghyeon-jeolmyeong", "dasan-tamjin"],
            ["hansi-common"]),
        lesson("h2-minyo", 11, "민요와 잡가", "지은이 없는 노래들",
            ["folk-sijipsari", "japga-yusanga", "goryeo-cheongsan"],
            []),

        // ── 고2·3 · 현대시 정리 카드 — 본문은 교과서·EBS 교재에서 ──────
        lesson("h2-m-north", 11, "백석과 이용악, 북방의 삶", "본문은 교재에서",
            ["baekseok-yeounangol", "baekseok-namsinuiju", "baekseok-huinbaram", "yongak-nalgeunjip"],
            ["north-common"]),
        lesson("h2-m-image", 11, "이미지의 시인들", "본문은 교재에서",
            ["gwanggyun-wasadeung", "gwanggyun-chuil", "chihwan-gitbal", "chihwan-saengmyeong"],
            ["image-common"]),
        lesson("h2-m-cheongrok", 11, "청록파와 서정주", "본문은 교재에서",
            ["mogwol-nageune", "jihun-seungmu", "dujin-hae", "jeongju-gukhwa", "jeongju-chucheonsa"],
            ["cheongrok-common"]),
        lesson("h2-m-sixties", 11, "김수영과 신동엽", "본문은 교재에서",
            ["suyeong-pul", "suyeong-nun", "suyeong-pokpo", "suyeong-gogung", "dongyeop-kkeopdegi"],
            ["sixties-common"]),
        lesson("h2-m-being", 11, "존재와 이름", "본문은 교재에서",
            ["chunsu-kkot", "chunsu-seosi", "sangbyeong-gwicheon", "donggyu-pyeonji"],
            ["being-common"]),
        lesson("h2-m-life", 11, "삶의 자리에서", "본문은 교재에서",
            ["gyeongnim-nongmu", "jaesam-chueok", "jaesam-gaeulgang", "jaegu-sapyeong", "gihyeongdo-binjip"],
            ["life-common"])
    ]);

    window.POETRY_GRADES = Object.freeze([
        { grade: 3, label: "초등 3학년", short: "초3" },
        { grade: 4, label: "초등 4학년", short: "초4" },
        { grade: 5, label: "초등 5학년", short: "초5" },
        { grade: 6, label: "초등 6학년", short: "초6" },
        { grade: 7, label: "중학 1학년", short: "중1" },
        { grade: 8, label: "중학 2학년", short: "중2" },
        { grade: 9, label: "중학 3학년", short: "중3" },
        { grade: 10, label: "고등 1학년", short: "고1" },
        { grade: 11, label: "고등 2·3학년", short: "고2·3" }
    ]);
})();
