(() => {
    "use strict";

    // 시집 차례표. 시 본문은 poems/<아이디>.js, 목록 화면용 요약은 poems-index.js에 있고
    // 여기서는 시집 한 권에 시 몇 편이 실리는지만 묶는다.
    // 학년 표시는 두지 않는다 — 실제 교과서 목차를 확인한 것이 아니라 난이도로만 순서를 매겼다.
    // 배열에 적힌 차례가 곧 "차례대로 읽기"의 순서다.
    const book = (id, title, note, poemIds) => ({ id, title, note, poemIds });

    window.POETRY_BOOKS = Object.freeze([
        book("g3-scene", "「호수」 외 세 편", "장면 하나가 시 한 편이 돼요",
            ["jiyong-hosu", "jiyong-byeoltong", "taeeung-gamjakkot", "jiyong-hongsi"]),
        book("g3-repeat", "「엄마야 누나야」 외 세 편", "같은 말이 왜 자꾸 나올까요",
            ["sowol-eommaya", "sowol-geumjandi", "deokchul-bompyeonji", "dongju-banditbul"]),
        book("g3-mimetic", "「햇비」 외 두 편", "소리와 모습을 글자로 옮겨요",
            ["dongju-haetbi", "dongju-chamsae", "jiyong-hongsi"]),
        book("g3-calling", "「새야 새야 파랑새야」 외 세 편", "대답 없는 것에게 말을 걸어요",
            ["folk-saeya", "folk-dara", "folk-dukkeobi", "sowol-eommaya"]),
        book("g3-asking", "「누가 바람을 보았나요」 외 두 편", "묻는 말로 시작하면 함께 생각하게 돼요",
            ["rossetti-baram", "dongju-nun", "folk-eodikkaji"]),

        book("g4-simile", "「나의 그림자」 외 세 편", "무엇에 빗대었는지 찾아요",
            ["stevenson-geurimja", "leejanghee-bomeun", "dongju-haetbi", "stevenson-bi"]),
        book("g4-persona", "「봄」 외 세 편", "사물이 사람이 되어 움직여요",
            ["dongju-bom", "dongju-jogaekkeopjil", "rossetti-baram", "deokchul-bompyeonji"]),
        book("g4-senses", "「분홍은 무엇일까요」 외 세 편", "눈·귀·코·혀·살갗으로 그린 시",
            ["rossetti-bunhong", "leebaek-jeongyasa", "dubo-chunyahuiu", "stevenson-geune"]),
        book("g4-speaker", "「굴뚝」 외 세 편", "시 속 사람의 자리를 찾아요",
            ["dongju-gulttuk", "kimyeongrang-omae", "jiyong-byeoltong", "dongju-jogaekkeopjil"]),
        book("g4-bittersweet", "「오줌싸개 지도」 외 세 편", "웃음 뒤에 숨은 마음",
            ["dongju-ojumssagae", "dongju-geojitburi", "dongju-chamsae", "jiyong-hongsi"]),

        book("g5-metaphor", "「나룻배와 행인」 외 세 편", "'~은 ~이다'로 곧장 말해요",
            ["manhae-narutbae", "dongju-sonyeon", "dongju-nun", "leejanghee-bomeun"]),
        book("g5-sound", "「돌담에 속삭이는 햇발」 외 세 편", "부드러운 소리와 센 소리",
            ["yeongrang-doldam", "dongju-bom", "kimyeongrang-omae", "dongju-haetbi"]),
        book("g5-empathy", "「천만 리 머나먼 길에」 외 두 편", "내 마음을 사물에 옮겨 놓아요",
            ["wangbangyeon-cheonmalli", "leegae-chokbul", "dongju-jogaekkeopjil"]),
        book("g5-flow", "「산유화」 외 세 편", "시가 흘러가는 길",
            ["sowol-sanyuhwa", "sowol-gaeyeoul", "dongju-saeroun-gil", "jiyong-byeoltong"]),
        book("g5-sijo", "「한산섬 달 밝은 밤에」 외 세 편", "석 줄에 담는 옛 노래",
            ["leesunsin-hansanseom", "yunseondo-ouga", "hwanghui-daechu", "leejeongbo-gukhwa"]),

        book("g6-irony", "「진달래꽃」 외 두 편", "겉말과 속말이 어긋나요",
            ["sowol-jindallae", "sowol-meonhuil", "sasol-dukkeobi"]),
        book("g6-paradox", "「복종」 외 두 편", "말이 안 되는데 뜻이 통해요",
            ["manhae-bokjong", "manhae-alsu", "manhae-narutbae"]),
        book("g6-symbol", "「서시」 외 두 편", "별 하나가 여럿을 가리켜요",
            ["dongju-seosi", "yuksa-cheongpodo", "nocheonmyeong-saseum"]),
        book("g6-contrast", "「자화상」 외 세 편", "빛깔과 처지를 나란히 놓아요",
            ["dongju-jahwasang", "yuksa-cheongpodo", "sowol-sanyuhwa", "nocheonmyeong-saseum"]),
        book("g6-compare", "「하여가」 외 세 편", "닮은 시와 다른 시",
            ["leebangwon-hayeoga", "jeongmongju-dansimga", "sowol-jindallae", "sowol-meonhuil"]),
        book("g6-oldsong", "「청산별곡」 외 세 편", "가장 오래된 우리 노래들",
            ["goryeo-cheongsan", "goryeo-gasiri", "gojia-guji", "jiyong-hyangsu"]),

        // 여기서부터는 배우는 것이 아니라 시인으로 묶는다. 시험은 아는 시인의 처음 보는 시를 내니까,
        // 익숙한 시 곁에 처음 보는 시를 한 편씩 두어 그 시인의 버릇을 익히게 한다.
        book("m1-jiyong", "「유리창 1」 외 세 편", "아는 시인, 처음 보는 시",
            ["jiyong-yurichang", "jiyong-hyangsu", "jiyong-hosu", "jiyong-byeoltong"]),
        book("m1-sowol", "「가는 길」 외 세 편", "헤어짐 앞에서 머뭇거리는 시",
            ["sowol-ganeungil", "sowol-jeopdongsae", "sowol-jindallae", "sowol-sanyuhwa"]),
        book("m1-era", "「빼앗긴 들에도 봄은 오는가」 외 두 편", "시대를 알고 읽기",
            ["sanghwa-ppaeatgin", "yuksa-cheongpodo", "dongju-seosi"]),
        book("m1-hyangga", "「제망매가」 외 두 편", "신라 향가 세 편",
            ["hyangga-jemangmaega", "hyangga-seodongyo", "hyangga-heonhwaga"]),
        book("m1-textbook", "「엄마 걱정」 외 두 편", "본문은 교과서에서",
            ["gihyeongdo-eomma", "kimjonggil-seongtanje", "sinseokjeong-meonnara"]),

        book("m2-manhae", "「님의 침묵」 외 세 편", "어긋난 말에 담은 님",
            ["manhae-nim", "manhae-narutbae", "manhae-bokjong", "manhae-alsu"]),
        book("m2-yuksa", "「절정」 외 두 편", "벼랑 끝에서 세운 뜻",
            ["yuksa-jeoljeong", "yuksa-kkot", "yuksa-cheongpodo"]),
        book("m2-yeongrang", "「모란이 피기까지는」 외 두 편", "찬란한 슬픔의 봄",
            ["yeongrang-moran", "yeongrang-doldam", "kimyeongrang-omae"]),
        book("m2-dongju", "「또 다른 고향」 외 두 편", "나를 들여다보는 시",
            ["dongju-ttodareun", "dongju-jahwasang", "dongju-seosi"]),
        book("m2-leaving", "「고향 앞에서」 외 한 편", "문턱에서 머뭇거리는 시",
            ["ojanghwan-gohyang", "yongcheol-tteonaganeun"]),
        book("m2-old", "「도산십이곡」 외 두 편", "시조 세 수와 고려 노래 둘",
            ["leehwang-dosan", "goryeo-dongdong", "goryeo-jeongseokga"]),

        book("m3-yuksa", "「광야」 외 두 편", "시간을 펼쳐 놓은 뜻",
            ["yuksa-gwangya", "yuksa-gyomok", "yuksa-jeoljeong"]),
        book("m3-dongju", "「참회록」 외 세 편", "거울을 닦는 시",
            ["dongju-chamhoerok", "dongju-sipjaga", "dongju-swipge", "dongju-seosi"]),
        book("m3-sowol", "「초혼」 외 두 편", "눌러 참기와 목놓아 부르기",
            ["sowol-chohon", "sowol-sakju", "sowol-jindallae"]),
        book("m3-modern", "「거울」 외 두 편", "가까운 것이 낯설어질 때",
            ["leesang-geoul", "jiyong-gohyang", "inhwan-sewol"]),
        book("m3-river", "「논개」 외 두 편", "흐르는 물에 얹은 뜻과 눈물",
            ["yeongro-nongae", "jisang-songin", "wangbangyeon-cheonmalli"]),
        book("m3-gasa", "「상춘곡」 외 두 편", "길게 이어지는 옛 노래글",
            ["geugin-sangchun", "seondo-eobu", "jeongcheol-gwandong"]),

        book("h1-jiyong", "「비」 외 세 편", "감정을 지운 자리",
            ["jiyong-bi", "jiyong-indongcha", "jiyong-jangsusan", "jiyong-yurichang"]),
        book("h1-two-faces", "「독을 차고」 외 세 편", "아는 이름의 낯선 시",
            ["yeongrang-dok", "yeongrang-buk", "yuksa-jayagok", "yeongrang-doldam"]),
        book("h1-dongju", "「길」 외 두 편", "담 저쪽의 나",
            ["dongju-gil", "dongju-gan", "dongju-chamhoerok"]),
        book("h1-leesang", "「오감도 시제1호」 외 한 편", "띄어쓰기를 없앤 까닭",
            ["leesang-ogamdo", "leesang-geoul"]),
        book("h1-hyangga", "「찬기파랑가」 외 두 편", "열 줄 노래의 짜임",
            ["hyangga-changiparang", "hyangga-anminga", "hyangga-jemangmaega"]),
        book("h1-joseon", "「용비어천가」 외 한 편", "나라의 노래와 한 사람의 노래",
            ["joseon-yongbi", "jeongcheol-samiin"]),
        book("h1-textbook", "「여승」 외 세 편", "본문은 교과서에서",
            ["baekseok-yeoseung", "hyeonseung-platanus", "gwangseop-bidulgi", "hyeonggi-nakhwa"]),

        book("h2-gwandong", "「관동별곡」 외 한 편", "금강산·동해·꿈",
            ["jeongcheol-gwandong-2", "jeongcheol-gwandong"]),
        book("h2-songmiin", "「속미인곡」 외 한 편", "두 여인의 대화",
            ["jeongcheol-songmiin", "jeongcheol-samiin"]),
        book("h2-gyuwon", "「규원가」 외 한 편", "여인이 쓴 여인의 노래",
            ["heo-gyuwonga", "jeongcheol-samiin"]),
        book("h2-nuhang", "「누항사」 외 한 편", "전쟁 뒤의 가사",
            ["bakinro-nuhangsa", "bakinro-seonsangtan"]),
        book("h2-nongga", "「농가월령가」 외 한 편", "열두 달 농사 노래",
            ["jeonghakyu-nongga", "goryeo-dongdong"]),
        book("h2-sijo-1", "「고산구곡가」 외 두 편", "산에 살아도 마음은 임금께",
            ["leei-gosan", "seondo-manheung", "seondo-gyeonhoeyo"]),
        book("h2-sijo-2", "「매화사」 외 두 편", "매화와 국화, 그리고 두꺼비",
            ["minyeong-maehwasa", "leejeongbo-gukhwa", "sasol-dukkeobi"]),
        book("h2-goryeo", "「서경별곡」 외 세 편", "이별의 세 목소리",
            ["goryeo-seogyeong", "goryeo-manjeonchun", "jeongseo-jeonggwajeong", "goryeo-gasiri"]),
        book("h2-hansi", "「사리화」 외 세 편", "참새와 황두, 텅 빈 성과 무궁화",
            ["jehyeon-sarihwa", "leesaek-bubyeongnu", "hwanghyeon-jeolmyeong", "dasan-tamjin"]),
        book("h2-minyo", "「시집살이 노래」 외 두 편", "지은이 없는 노래들",
            ["folk-sijipsari", "japga-yusanga", "goryeo-cheongsan"]),

        book("h2-m-north", "「여우난골족」 외 세 편", "본문은 교재에서",
            ["baekseok-yeounangol", "baekseok-namsinuiju", "baekseok-huinbaram", "yongak-nalgeunjip"]),
        book("h2-m-image", "「와사등」 외 세 편", "본문은 교재에서",
            ["gwanggyun-wasadeung", "gwanggyun-chuil", "chihwan-gitbal", "chihwan-saengmyeong"]),
        book("h2-m-cheongrok", "「나그네」 외 네 편", "본문은 교재에서",
            ["mogwol-nageune", "jihun-seungmu", "dujin-hae", "jeongju-gukhwa", "jeongju-chucheonsa"]),
        book("h2-m-sixties", "「풀」 외 네 편", "본문은 교재에서",
            ["suyeong-pul", "suyeong-nun", "suyeong-pokpo", "suyeong-gogung", "dongyeop-kkeopdegi"]),
        book("h2-m-being", "「꽃」 외 세 편", "본문은 교재에서",
            ["chunsu-kkot", "chunsu-seosi", "sangbyeong-gwicheon", "donggyu-pyeonji"]),
        book("h2-m-life", "「농무」 외 네 편", "본문은 교재에서",
            ["gyeongnim-nongmu", "jaesam-chueok", "jaesam-gaeulgang", "jaegu-sapyeong", "gihyeongdo-binjip"])
    ]);
})();
